bioconda/bioconda-utils
bioconda/draw_dag.sh

This PR makes the dag subcommand more flexible. It allows to pipe out the dag, and supports multiple formats. So far, gml and dot are implemented, but anything supported by networkx can be added.

Provide a more flexible dag output.

---

bioconda_utils/cli.py
bioconda_utils/example_config.yaml
bioconda_utils/utils.py
setup.py

@bioconda/core, please check this out and post your opinion.
This PR integrates docker building into bioconda-utils itself. This has two advantages:
1. With our SUBDAG setup in travis, we have to launch the build process for each subdags. Previously, even empty subdags have triggered the docker image pull. Now, we can decide to pull the image only if the subdag is not empty. This should provide a nice speedup.
2. It becomes easier to manually build packages within the docker image. All you need to do is to add the flag --docker. Thanks to the way the image is build, it can share the `conda-bld` directory with the host, so that the package will be available on the host system.
I decided to switch to the docker image `continuumio/conda_builder_linux` from @msarahan. As far as I know, this …

Allow building inside docker container via the flag --docker.

---

bioconda_utils/build.py

This can be removed once all packages are rebuild with conda-build 2.x

Add --no-build-id to allow long path names in recipes

---

bioconda_utils/build.py
bioconda_utils/utils.py

This PR uses `git fetch origin master` and `git diff FETCH_HEAD` for more portable comparisons with master branch than `git show master:filename`. This now works on travis-ci which uses a detached head in its cloned git repos. This allows the `--quick` option to work on travis-ci as well as locally.
The `--quick` option does not enable or disable recipes for building. That's the job of `filter_recipes`. Rather, `--quick` just reduces the set of recipes that are considered by `filter_recipes` to just those that have recently changed.
The other item in this PR: previously, a recipe would be filtered out if its build string (name-version-build) was already found in one of the configured channels (bioconda, conda-forge, defaults, r). This is not what we want though, because this precludes …

Fix for --quick and channel filtering

---

bioconda_utils/build.py

xrefs:
- https://github.com/bioconda/bioconda-recipes/pull/2973
- https://github.com/bioconda/bioconda-recipes/issues/2957
and probably others I can't find at the moment. Several fixes here: the mulled-build failure detection (based string in stderr) was happening *after* the logger reported success, which was confusing. Second, by returning False right away, we didn't have a chance to log the errors within `build()`. And third, the logger level for reporting those mulled-build errors was set to debug rather than error.
ping @bgruening, @mvdbeek, @martin-mann

mulled-build exit checks

---

bioconda_utils/docker_utils.py

On OSX /var is a symlink to /private/var. This causes problems for
mounting in Docker unless the symlinks are resolved first. See:
* https://docs.docker.com/docker-for-mac/osxfs/#/namespaces
* https://forums.docker.com/t/getting-mounts-denied-on-previously-working-container-after-upgrading-to-v1-12-0-beta18-3-gec40b14/17546/8
* https://forums.docker.com/t/docker-for-mac-beta-does-not-handle-symlinks-when-mounting-volumes/10955/9

Resolve symlinks in tempdir path

---

docs/source/generate_docs.py

docs generation is [currently failing](https://travis-ci.org/bioconda/bioconda-utils/jobs/188950019):
```
Exception occurred:
File "/home/travis/build/bioconda/bioconda-utils/docs/source/generate_docs.py", line 178, in setup
notes = 'Notes\n-----\n\n' + notes
TypeError: Can't convert 'list' object to str implicitly
[.......]
make: *** [html] Error 1
```
this commit adds a check to handle the cases when `notes` is a list.
but perhaps more concerning is that the builds are marked as "successful" even when the doc generation fails, is this intentional ?
pinging @daler

handle cases when notes is a list

---

bioconda_utils/pkg_test.py

Replace $PREFIX with /usr/local
This is the location of the file inside of Docker
ping @ThomasWollmann

enable tests with PREFIX in the docker tests

---

bioconda_utils/cli.py

This moves some of the functionality from PR bioconda/bioconda-recipes#3891 into bioconda-utils. The benefit is that `scripts/travis-run.sh` will be simpler again, and the functionality becomes available locally. In the long run, it can also deprecate `--quick`, since it is more general.

Filter recipes by git range

---

bioconda_utils/utils.py

This adds a regex to parse out the git version in a way compatible with Apple git, since under macOS the git version is reported like this: `git version 2.10.1 (Apple Git-78)`.

use regex to parse out git version for OSX git

---

bioconda_utils/cli.py
bioconda_utils/utils.py

This PR allows `modified_recipes` to also detect recipes that were newly blacklisted in the provided git range. Otherwise a recipe would have be modified in some way before being detected.

Blacklist handling

---

bioconda_utils/cli.py
bioconda_utils/github_integration.py
bioconda_utils/linting.py
bioconda_utils/templates/lint_failure.md
bioconda_utils/templates/lint_success.md
bioconda_utils/utils.py
setup.py

This PR implements the pushing of comments with lints to github. The new functionality is intended to run via our new buildkite setup, not via travis (although it would work for travis as well, as long as the build comes from the main repo).

Optionally push linting comments to github.

---

bioconda_utils/cli.py

In other words, if a recipe is considered modified because it has been deleted in a PR, we don't want to lint it.

Constrain filtered recipes to those where the meta.yaml file exists.

---

bioconda_utils/build.py
bioconda_utils/cli.py
bioconda_utils/pkg_test.py
bioconda_utils/upload.py
test/test_utils.py

This PR moves the uploading of mulled images into bioconda-utils, and exposes a new CLI flag `--mulled-upload-target NAME`. If this is given (e.g. with `NAME=biocontainers`), bioconda-utils will handle the upload.
This PR shall **not** be merged until bioconda/bioconda-recipes#4479 has been tested and merged.

[WIP] Mulled upload

---

bioconda_utils/build.py

This will help with bulk updates: bioconda-utils will try to build as many recipes
as possible until the timeout occurs. Since they are immediately uploaded (of course not in PRs), subsequent builds won't need to rebuilt them when they succeeded in a previous build.
Hence, bulk updates can be easily handled by fixing recipes in an iterative process, without blacklisting.
On the bioconda-recipes side, I intend to handle this via creating pull requests to special bulk/* branches,
such that we don't have failures in master.
In total, I have the hope that this will mostly solve our bulk update issues, such that we can finally proceed to Python 3.6 and R 3.4.

Upload packages immediately after build

---

bioconda_utils/utils.py

Otherwise, we cannot debug parsing errors in conda-build that lead to exit(1).

Print each filter message in one row.

---

bioconda_utils/build.py
bioconda_utils/utils.py

An attempt to fix the apparently interleaved build logs on travis that only happens on osx.

Enable build ids

---

bioconda_utils/cli.py

currently if the PR doesn't modify any recipe the build throws a exception:
```python
16:20:27 BIOCONDA INFO No recipe modified according to git, exiting.
Traceback (most recent call last):
File "/anaconda/bin/bioconda-utils", line 11, in <module>
load_entry_point('bioconda-utils==0.10.0', 'console_scripts', 'bioconda-utils')()
File "/anaconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 385, in main
argh.dispatch_commands([build, dag, dependent, lint])
File "/anaconda/lib/python3.5/site-packages/argh-0.26.2-py3.5.egg/argh/dispatching.py", line 328, in dispatch_commands
File "/anaconda/lib/python3.5/site-packages/argh-0.26.2-py3.5.egg/argh/dispatching.py", line 174, in dispatch
File "/anaconda/lib/python3.5/site-packages/argh-0.26.2-py3.5.egg/argh/dispatching.py", line 277, in …
```

return empty list instead of None

---

bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/build.py
bioconda_utils/pkg_test.py
bioconda_utils/utils.py
test/test_pkg_test.py
test/test_utils.py

This PR allows to define a custom base image for mulled via
```
extra:
container:
base: "<baseimage>"
```

Custom base image definition via meta.yaml.

---

bioconda_utils/utils.py

This is common, because we sometimes store multiple versions of the same recipe in subdirectories.
Hence, it should not fail.
The regression was introduced in PR #114. This change should not affect the main benefit of that PR. Since we still use a set, there cannot be multiple builds of the same recipe.

Remove check for the case of having multiple recipes for the same package name.

---

bioconda_utils/build.py
bioconda_utils/pkg_test.py
bioconda_utils/utils.py

If disk space is less than 10 MB, all conda packages are cleaned up.

Improved cleanup

---

bioconda_utils/build.py

Instead of allowing to set an arbitrary image, we allow to specify:
```
extra:
container:
extended-base: true
```

Support a switch for enabling the extended base image.

---

bioconda_utils/lint_functions.py

@johanneskoester @bgruening anything else you can think of to look for in the linter?

add linter for noarch

---

bioconda_utils/build.py
bioconda_utils/docker_utils.py
bioconda_utils/lint_functions.py
docs/source/linting.rst

1. Fix noarch building (use correct output folder in the container) (see PR bioconda/bioconda-recipes#5014).
2. Keep conda from building subdirectories by explicitly specifying meta.yaml (see PR bioconda/bioconda-recipes#5011).

Fix noarch errors. Fix sub-recipe problems.

---

bioconda_utils/build.py
bioconda_utils/docker_utils.py
test/test_utils.py

xref: bioconda/bioconda-recipes#4997
Further, this PR fixes a missing propagation of noarch information to the docker container.

Fix determination of docker output path.

---

bioconda_utils/utils.py

Such that we can set it in our global travis configuration.

Whitelist MACOSX_DEPLOYMENT_TARGET

---

test/test_utils.py

@nsoranzo turns out conda-build handles rendering differently based on whether the env var is already set or not. This PR makes the test handle both cases. I haven't worked out exactly why the error is different depending on the situation, but in both cases the env is properly sandboxed.

fix test to handle cases where GITHUB_TOKEN is already set

---

bioconda_utils/build.py
bioconda_utils/cli.py
bioconda_utils/docker_utils.py
bioconda_utils/linting.py
bioconda_utils/pkg_test.py
bioconda_utils/upload.py
bioconda_utils/utils.py
docs/source/contrib-setup.rst
docs/source/contribute-a-recipe.rst
docs/source/index.rst

This incorporates the changes in #153.
- paths to conda respect CONDARC
- do recipe filtering first, and only build docker container if there's something to build
- optionally keep docker image when testing
- fix some permission issues from the docker container (changes to the build script used in the docker container)
- pep8 cleanup
- overhaul docs to reflect the new changes

support for bioconda-recipes #5227

---

.travis.yml
README.md
build-docs.sh
docs/source/contrib-setup.rst
docs/source/contribute-a-recipe.rst
travis-run.sh

travis-ci is timing out on master branch when running tests and then building docs. This splits the tests and docs into separate tasks in the matrix.

split tests and docs into separate travis-ci jobs

---

bioconda_utils/docker_utils.py

... to prevent crashes with versions < 1.13.0 due to the --network flag.
See [#5387](https://github.com/bioconda/bioconda-recipes/issues/5387) for details.
This parses the string returned by `docker --version`, which stayed the same between version 1.6.2 and 1.12.6 of docker. The result of the `docker version` subcommand did not.
I ran [travis tests](https://travis-ci.org/HenningTimm/bioconda-utils/builds/260268687) on a fork of this repo. Most of them passed, but the linux test for the docs failed. I am not sure why.

Added version check for docker 

---

bioconda_utils/pkg_test.py

Running `bioconda build recipes --docker --mulled-test...` with `CONDA_ROOT=/Users/username/.biocondaenv` fails within the mulled build when `/users/username` can't be found (note missing capitalization).
The cause is that the directory is passed from `pkg_test.py` through the various layers (galaxy, involucro, docker, etc) as a file URI: `file://Users/username/.biocondaenv/conda-bld`. This URI is incorrect, as it references the file `/username/.biocondaenv/conda-bld` on the host `Users`.
Somewhere within `conda-build`, the hostname portion is normalized and looses its capitalization, which then leads to the file-not-found condition.
Correct usages of the file URI are dropping the authority field entirely (`file:/Users/username`), setting the hostname explicitly …

Fix mulled-test fails on uppercase in top dir name

---

bioconda_utils/bioconductor_skeleton.py
bioconda_utils/cli.py

This PR moves the `bioconductor_skeleton.py` script from bioconda-recipes to bioconda-utils. It is now called with `bioconda-utils bioconductor-skeleton`. 
Importantly, it also now handles data-heavy packages by building a `post-link.sh` script instead of a `build.sh` script. This is the strategy tested out in https://github.com/bioconda/bioconda-recipes/pull/5485. The post-link script is executed at install-time, not build-time, which means the package data is not included in the conda package. This avoids consuming the limited space on the bioconda channel while still allowing large, data-heavy Bioconductor packages to be installed via conda.
Data packages are detected as those stored under the "data/annotation" subdirectory on the Bioconductor servers (e.g., …

Bioconductor skeleton updates

---

bioconda_utils/bioconductor_skeleton.py
bioconda_utils/cli.py

This PR reintroduces the minimum R version spec (since some packages are now requiring R versions >3.4) and now uses jinja templating for the version and name.  This is in preparation for moving all Bioc packages to 3.5 (and then hopefully to 3.6 at the end of October).

Bioconductor skeleton improvements

---

bioconda_utils/lint_functions.py
docs/source/linting.rst

This PR ensures that new recipes pin [a subset of] dependencies listed in `env_matrix.yml`.
Once this is working well in practice, we can move towards changing our pinning to match https://github.com/conda-forge/conda-forge.github.io/blob/0661e2ecf4b213ddf36350ca100a5a820eb17eb7/scripts/pin_the_slow_way.py#L40-L85, both in terms of content and format (in that they include the dependency name in the templated variable).
@bgruening this should hopefully cut down on the number of comments you have to make on PRs ;)

Lint pinning

---

bioconda_utils/lint_functions.py
bioconda_utils/linting.py
test/test_linting.py

Linting for recipes with empty `build:` sections failed since `meta.get('build', {})` is `None` in that case and thus does not support any `dict`-operations. Testcase and fix added.
Also added a debug log for every recipe before executing the lint functions to help debugging batch linting. @johanneskoester

lint: fix: crash at empty build section

---

bioconda_utils/utils.py
test/test_utils.py

`meta.yaml` sections may be empty and thus will be an empty `str` when parsed by `conda-build`. Hence accessing `meta[key]` in `get_meta_value` will fail since `meta` can be `""` which cannot be subscripted by another `str`, i.e., section name.
Use case that will fail:
```yaml
extra:
container:
extended-base: true  # [py27]
```
Due to the selector, `container` will be empty for Python 3 builds.

build: fix: sections may be empty in get_meta_value 

---

.travis.yml

Error reported by @nsoranzo:
> I think something broke bioconda-utils lint (and probably more): https://travis-ci.org/bioconda/bioconda-recipes/jobs/295247753
The reason is that `pytz` was changed to be a `noarch: python` package but for Bioconda `Miniconda 4.2.12` has been used as the starting point on Travis. `noarch: python` support is a `conda 4.3` things hence `pytz=2017.3=1` somehow wasn't correctly installed by `conda 4.2.12` when trying to update itself.
`conda ==4.3.21` is specified in `bioconda_utils-requirements.txt`. So, I guess it might be ok to use `Miniconda 4.3.21` for Travis?

travis: update Miniconda to 4.3.21

---

docs/source/guidelines.rst

Should this label ``shasum -a 256 ...`` as typical on OSX? Is ``sha256sum`` the more common tool on Linux (I have both)?

Recommend sha256 over md5

---

bioconda_utils/bioconductor_skeleton.py
bioconda_utils/cli.py

1) bioconductor skeleton no longer pins `r-base`
2) warning is logged if a recipe has changed but is still in a blacklist

minor tweaks

---

docs/source/contribute-a-recipe.rst

When just running the two steps described in the current docs for the fork workflow, the Travis build fails when pushing out changes on a new or updated branch, based on the newest upstream master -- it gets confused by the lack of commits in the fork's master branch. So whenever updating the local master branch from upstream, these changes should also be pushed out to the fork (origin):
`git push origin master`
I don't think this is necessary for the clone, that should only be on the local machine. But I haven't used that workflow yet, so I'm not absolutely sure.

add `git push origin master` to fork repo update docs

---

bioconda_utils/lint_functions.py

Build numbers should only be comparable inside a single conda channel.
This PR removes the build number comparison for `in_other_channels`, which in turn can detect some more duplicate packages with this change.

lint: fix: build numbers not comparable across channels

---

bioconda_utils/build.py
bioconda_utils/docker_utils.py

This is needed for openmpi builds xref: https://github.com/bioconda/bioconda-recipes/pull/6649
and is also be done by conda-forge in similar cases: https://github.com/conda-forge/pytrilinos-feedstock/blob/89340939dc0591e3a31a0ef92fe4367aeb56a9cf/ci_support/run_docker_build.sh#L66
It will prolong our build-time, so we could do this in the base image from which we derive here. A more elaborated stunt would be to make it more flexible and add this package as a yaml-metadata and we install this on request ... this would mean deeper code changes and I'm not sure how frequent this use-case is.

RFC - adding openssh-clients

---

build-docs.sh

Use TRAVIS_PULL_REQUEST_SLUG, rather than TRAVIS_REPO_SLUG. This supports the fork-and-pull-request model by avoiding doing anything with the encrypted vars.

use TRAVIS_PULL_REQUEST_SLUG to detect forks

---

bioconda_utils/bioconductor_skeleton.py

Adds some whitespace to bring the bioconductor meta.yaml files closer to the format generally used in Bioconda (from what I've seen).
At least it fixes syntax highlighting in vim :-)

Whitespace cleanups in the generated meta.yaml.

---

docs/source/guidelines.rst

BLAST is now built on OSX and Linux from scratch with nearly no OS dependent stuff, so no longer good example.
Merge when bioconda/bioconda-recipes#6073 has been merged.

Remove BLAST example from docs (outdated by #6073)

---

bioconda_utils/lint_functions.py
test/test_linting.py

This extends the `missing_*` lint functions to also test whether the requested values actually have content. E.g., the following cases can now be caught too:
```yaml
source:
sha256: ""
```
```yaml
test:
```
```yaml
about:
home: ""
```

lint: test for empty values in `missing_*` lints

---

bioconda_utils/cli.py
bioconda_utils/docker_utils.py
bioconda_utils/utils.py
test/test_utils.py

This PR simplifies the Docker configuration and uses the new `bioconda/bioconda-utils-build-env` image.

use bioconda/bioconda-utils-build-env image

---

bioconda_utils/bioconda_utils-requirements.txt
travis-setup.sh

This does three things:
1. Add `numpy` explicitly to the requirements (previously implicitly by `pandas`). That way we should get `numpy` from `conda-forge` instead of from https://repo.continuum.io/pkgs which would
* reduce the dependency on https://repo.continuum.io/pkgs,
* use the `openblas` build instead of the `mkl` one.
That way we can avoid downloading/installing that big `mkl` package and thus skim maybe 20-30 seconds setup time as well as a couple of hundreds MB from the Docker image.
The reason we didn't get `numpy` from `conda-forge` in the first place is described here: https://github.com/conda/conda/issues/6199#issuecomment-344097039.
2. Update to `beautifulsoup4 4.6.0`. The previous version is not available on `conda-forge` since its `beautifulsoup4` package only got added …

Use more conda-forge pins and slim down the Docker image

---

bioconda_utils/bioconductor_skeleton.py

I tried the following on macOS, but surprisingly it failed:
```
conda create -y -n test1 bioconductor-genomeinfodbdata
```
It turns out that the [expected](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-genomeinfodbdata/post-link.sh#L7) and observed MD5 are different.
```
$ wget -q http://bioconductor.org/packages/3.6/data/annotation/src/contrib/GenomeInfoDbData_0.99.1.tar.gz
$ md5sum GenomeInfoDbData_0.99.1.tar.gz 
47c68c7ba79de1c309a5b6009bbc0c71  GenomeInfoDbData_0.99.1.tar.gz
```
Thus this should also fail on Linux, but it doesn't because the conditional statement always evaluates to TRUE. I updated the conditional statement for Linux based on this [SO answer](https://unix.stackexchange.com/a/254875/232582) so that it fails if the downloaded tarball does …

Fail on Linux if Bioconductor data package has mismatched md5.

---

bioconda_utils/bioconductor_skeleton.py

On Ubuntu, a user library is automatically set, e.g. `~/R/x86_64-pc-linux-gnu-library/3.4`. When I install a Bioconductor data package, e.g. GenomeInfoDb, it gets install in my Ubuntu user library instead of in the conda R library.
This PR updates the `post-link.sh` file created by `bioconductor-skeleton.py` to install the Bioconductor data package in the conda R library path. I tested that this works on Ubuntu.

Install Bioconductor data packages in conda R library.

---

bioconda_utils/bioconductor_skeleton.py

Incorporates #230. Addresses #236.
There were some errors in checking the response status codes.

bioconductor skeleton: fixes for tarball download handling

---

bioconda_utils/bioconductor_skeleton.py

A minor oversight in a previous commit introduced a bug found by @jdblischak in https://github.com/bioconda/bioconda-utils/pull/237#issuecomment-350775885.

bioconductor: fix package_lower definition

---

bioconda_utils/bioconductor_skeleton.py

xref: #234 #235 
This PR adds a template `pre-unlink.sh` file for Bioconductor data packages that runs prior to removing the package from the conda environment. Without this file, the R package remains installed and accessible in `$PREFIX/lib/R/library` even after it has been removed.
It also makes two minor edits to the `post-link.sh` file:
1. Removes indentation from the line that defines `MD5`
1.  The subdirectory within `$PREFIX/share` that was created to download the tarball is deleted instead of only deleting the tarball

Add template pre-unlink.sh for Bioconductor data packages

---

bioconda_utils/lint_functions.py
docs/source/linting.rst

The `uses_setuptools` lint suggests to remove `setuptools` dependencies.
But `setuptools` can be a run requirement if a Python package
* uses `pkg_resources` (which is part of `setuptools`),
* uses `setup(entry_points={"console_scripts": [...]})` but doesn't have all those entry points replaced by Conda-created entry points in `meta.yaml` (which thus automatically use `pkg_resources` unlike the Conda-created ones),
* (very unlikely: imports `setuptools` (other than in `setup.py`)).
The previous wording `'setuptools may not be required'` let contributor to unconditionally remove `setuptools` from run/build requirements, I suppose because
* `may not` is more of a "prohibition" phrase,
* `be required` doesn't state we're only talking about run requirements.
This PR fixes and clarifies that …

lint: disable uses_setuptools

---

bioconda_utils/cli.py

This is a follow-up to #244.
I think that `bioconda-utils bioconductor-skeleton` should, by default, create default CRAN skeleton recipes. These in turn should be separately evaluated and determined if they are appropriate for bioconda or conda-forge depending on if they are bio-related or not. Then, 
bioconda: `bioconda-utils clean-cran-skeleton <recipe> --no-windows`
conda-forge: `bioconda-utils clean-cran-skeleton <recipe>`.
This is currently a WIP because `bioconda-utils clean-cran-skeleton` is currently not idempotent -- running it twice gives twice the `extra:maintainers:` blocks and twice the `about:license_file:` lines. Pretty sure the solution is parsing the yaml into dicts, but of course this gets annoying with jinja2 templating.

[WIP ] cran skeleton cleaning

---

bioconda_utils/build.py
test/test_utils.py

xref https://github.com/bioconda/bioconda-recipes/pull/7241, ping @johanneskoester and @bgruening. 
Rather than special-case `bioconda-utils`, this skips mulled-build for any recipe depending on conda. Should allow a `bioconda-utils` conda package to be built.

Skip mulled-build test for conda-dependent recipes

---

bioconda_utils/build.py

This is to fix a (non-critical) exception that occurred when building bioconda-utils (see [here](https://circleci.com/gh/bioconda/bioconda-recipes/429)).

Do not upload mulled image if tests have been skipped.

---

bioconda_utils/bioconda_utils-requirements.txt

The macOS queue for `conda-forge` on Travis CI was cleared 🍻. So we are now able to use the latest `conda 4.3.x` release!
IMO, updating to `conda 4.3.33` as soon as possible is important due to https://github.com/conda/conda/pull/6766.

requirements: update conda to 4.3.33

---

bioconda_utils/docker_utils.py

If Docker is not installed, simulate-travis.py fails in a somewhat confusing way.
This still shows a nasty exception, but a meaningful error is logged first.

Catch any error from running "docker --version"

---

pip-test-requirements.txt
test/test_utils.py

`pytest 3.4`(just released on `conda-forge`) introduced a [breaking change](https://docs.pytest.org/en/latest/logging.html#incompatible-changes-in-pytest-3-4) so that `caplog` doesn't capture `INFO` messages on default in `test/test_utils.py::TestSubdags::test_subdags_more_than_recipes`, which thus failed.

test: pytest>=3.4 compat: capture >=INFO messages

---

bioconda_utils/lint_functions.py
test/test_linting.py

The linter currently request to pin run-only dependencies. But if those dependencies are not required/directly pulled in during the build phase, the built package shouldn't have those run constraints.
(The second commit doesn't change behavior and is just to make the code a bit clearer (I hope).)

lint: dont' require pin for run-only deps

---

docker-entrypoint
docker-entrypoint-source

This is just a very minor change to make the `source` part of the Docker entrypoint reusable from outside the entrypoint.
Could be used in https://github.com/bioconda/bioconda-recipes/pull/7684/files/d5af76c8c779dcde05dce44ab52c724574879c6c#diff-1d37e48f9ceff6d8030570cd36286a61R50.

docker: split entrypoint in source/exec parts

---

docs/source/conf.py
docs/source/generate_docs.py
docs/source/templates/readme.rst_t
docs/source/templates/recipes.rst_t

- Templates for recipes and readme pages are now in separate files
- Shows progress as it's working (no more `print()` calls)
- Using Jinja for formatting logic
- Adds text from `about:description` field
- Escapes text from `notes`, `description` and `summary`
- Shows new `extra:identifiers` links (xref bioconda/bioconda-recipes#7940)
- Adds parallel generation of README.rst (call `make html SPHINXOPTS="-j16"` for 16 threads)

Refactor generate_docs 

---

docs/source/contribute-a-recipe.rst
docs/source/faqs.rst

Previously we had recommended enabling CircleCI for contributors' forks, but after some testing I confirmed that's what was causing all the "no macOS plan" issues. So this PR changes that recommendation.

docs for circle-ci macos

---

bioconda_utils/build.py
bioconda_utils/utils.py

The first three commits are some minor fixes.
The last two fix handling of dependencies by considering all requirements from `build`, `host`, as well as `run` environments. To avoid the previous workaround of only considering `host` due to cyclic dependencies of some existing recipes, this detects those dependency cycles and marks all packages of a cycle as `failed` (+ skipping any downstream packages, of course).

Handle dependency cycles

---

bioconda_utils/bioconda_utils-requirements.txt

The current `conda-forge-pinning` has some important changes in comparison to the ones we are currently using, namely updated `boost` and more strictly pinned `perl`. See the full changeset at https://github.com/conda-forge/conda-forge-pinning-feedstock/compare/86ded4c96afa1d2fd63d6295d91be1a9fc96839a...5781b888537cf9c30a039a6a793d37ff56f88c56.
We should discuss whether we should always use the latest `conda-forge-pinning` version or update manually. There are pros and cons for both strategies.

requirements: update to conda-forge-pinning 2018.07.18

---

bioconda_utils/cli.py

The current output below leaves the user wondering if linting passed as there's no summary output when it is successful.
```
bioconda-utils lint recipes config.yml --git-range master
21:54:00 BIOCONDA INFO Recipes newly unblacklisted:
21:54:00 BIOCONDA INFO Recipes to consider according to git: 
recipes/<recipe>
recipes/<recipe>
21:54:01 BIOCONDA INFO Recipes to lint:
recipes/<recipe>
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Adding in variants from internal_defaults
Adding in variants from /tmp/miniconda/miniconda/conda_build_config.yaml
Adding in variants from /tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/biocon …
```

Log when linting was successful.

---

Dockerfile
bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/docker_utils.py

Fixes the failing `test_build_container_default_gcc` by updating `conda` to `4.5.11`. That version fixes an incompatibility of `conda config` with a newer `ruamel.yaml` release. The error didn't show up because the error stream for `conda config` was piped to `/dev/null`.
This also updates `conda-build` to `3.14.4` which gives us
https://github.com/conda/conda-build/blob/3.14.4/CHANGELOG.txt#L81:
> * add ``tags``, ``identifiers``, and ``keywords`` to about section. Tie them into channeldata.json. #3091
which will be helpful in future.

update deps: conda=4.5.11 and conda-build=3.14.4

---

bioconda_utils/cli.py
docs/source/index.rst

This would previously have thrown an unitialized variable error. In addition this PR fixes a syntax error in index.rst, leading to a broken paper link.

Remove deprecated log message in case of empty linting job.

---

bioconda_utils/bioconda_utils-requirements.txt

Xref: https://github.com/bioconda/bioconda-recipes/issues/8947
This updates conda-forge-pinning to what is currently the most recent version. Most important to me is that this should result in builds for R 3.5.1. There are of course [other changes](https://github.com/conda-forge/conda-forge-pinning-feedstock/compare/5781b888537cf9c30a039a6a793d37ff56f88c56...e6ee6b2d76d590553937da9d5ae36ad1a13787aa) that may be important, in particular what appears to be gcc7 support depending on environment variables.

Bump conda-forge-pinning to 2018.09.20, which adds build support for R 3.5.1

---

bioconda_utils/build.py
bioconda_utils/cli.py

This should fix builds in `bulk` and any other environment where `--git-range` is not specified. Previously, the first channel in the channels list in the config file was checked to ensure that packages that already existed weren't built. Since the channel order was changed, this now means that `conda-forge` is checked against rather than `bioconda`. It's probably good to check against `conda-forge`, but especially for the `bulk` branch we need to check the `bioconda` channel as well. This PR causes up to the first 2 channels in the config file to be checked against before building/uploading. This will fix builds in the `bulk` branch. Additionally, this adds a `--check-channels` option to `bioconda-utils build`, so this can be directly changed by users (or the script given to circleci). …

Expose check_channels on the CLI and check the first 2 by default.

---

bioconda_utils/bioconductor_skeleton.py

This modifies the bioconductor skeleton in two important ways:
1. For packages not requiring compilation, it makes them `noarch: generic`. The same strategy is already being taken on conda-forge.
2. Compilers specified by environment variables are injected into the build scripts. This is something that I've noticed needing to do with some CRAN packages on conda-forge. Note that this mostly makes sense if you're running in a docker container, since otherwise it'll modify any `~/.R/Makevars` that already exists, which could obviously be problematic.
BTW, there aren't any C++14 bioconductor packages yet, though there are a number of them in CRAN. Injecting the environment variable for that is mostly for future-proofing.

generic and compilers for bioconductor packages

---

bioconda_utils/lint_functions.py

Also add the name of the output causing the lint to the result (visible only in full report)

Fix `noarch: False` triggers lint fail

---

bioconda_utils/build.py
bioconda_utils/cli.py
docs/source/build-system.rst

This will end up being used in `bulk` to add a gcc7 label to bioconductor packages.

Start supporting the BIOCONDA_LABEL env variable

---

bioconda_utils/bioconductor_skeleton.py

This fixes an issue I inadvertently introduced back in October when I updated the bioconductor skeleton. Part of the compiler injection stuff that goes into `build.sh` was preventing `dedent()` from stripping white space and resulting in files with a bunch of extra white space in them. It's a low priority fix, but it's been bugging me for a while.

Copy over bioconductor skeleton fixes from gcc7

---

docs/source/index.rst

Reverts bioconda/bioconda-utils#393
The additional conda-forge label is only needed when building packages, because the main label was removed from toolchain. For end users everything should be fine.

Revert "update docs to reflect changes in channel setup."

---

.circleci/setup.sh
Dockerfile
bioconda_utils/example_config.yaml
bioconda_utils/utils.py
docs/source/updating.rst
test/test-config.yaml
test/test_utils.py

This adds some documentation about `bioconda-utils update-pinning` using deepTools as an example.
I've also removed all of the last remnants of the `conda-forge/label/cf201901` label.

Pinning docs

---

test/test_bioconductor_skeleton.py

This should speed up the bioconductor tests by ~33% (at least it does in testing). These still rely heavily upon internet sites, which are the slowest components (most of the time is spent waiting for sites to respond).

Refactor bioconductor test

---

docs/source/cb3.rst
docs/source/guidelines.rst
docs/source/troubleshooting.rst

The guidelines for python still mentioned the use of conda-build 2.x over conda-build 3. Bioconda now uses conda-build 3. This PR rectifies the docs to point users to the correct version of conda-build for use with bioconda. This should fix https://github.com/bioconda/bioconda-recipes/issues/10311
It also fixes a line about noarch packages. Per the linter, noarch packages are required for pure python packages. I'm not sure in what other circumstances noarch packages are allowed / required. If someone could chime in on there, that would be great :-).

Remove conflicting information about conda-build 2

---

bioconda_utils/update.py
bioconda_utils/utils.py
test/helpers.py
test/test_hosters.py
test/test_utils.py

The use of yaml.load(input) is deprecated, because of an security exploit see:
https://msg.pyyaml.org/load
All use of 'yaml.load(input) has been changed to 'yaml.safe_load(input)', all tests seems to pass.
This resolve #462

Changed the use of 'yaml.load(input)' to 'yaml.safe_load(input)':

---

docs/source/contrib-setup.rst
docs/source/contribute-a-recipe.rst
docs/source/index.rst

@bioconda/core Can someone do some sanity checking on this and see if I've missed anything?
Needed for https://github.com/bioconda/bioconda-recipes/pull/14395
Closes https://github.com/bioconda/bioconda-recipes/issues/1

Update docs regarding becoming a new member

---

.circleci/build-docs.sh
bioconda_utils/__init__.py
bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/bioconductor_skeleton.py
bioconda_utils/docker_utils.py
bioconda_utils/githandler.py
bioconda_utils/sphinxext.py
bioconda_utils/utils.py
docs/Makefile
docs/source/cb3.rst
docs/source/conf.py
docs/source/contrib-setup.rst
docs/source/contribute-a-recipe.rst
docs/source/faqs.rst
docs/source/generate_docs.py
docs/source/guidelines.rst
docs/source/troubleshooting.rst
docs/source/updating.rst

- adds BIOCONDA_FILTER_RECIPES to avoid rebuilding all recipe data locally
- moves `generate_docs` to `bioconda_utils.sphinxext`
- removes a bunch of constants and makes them configurable in `conf.py`
- fixes a bunch more links
- improve api docs
- autogenerate sectionlabels
- fix regression in repodata (disk cache accidentally disabled)

Docs update

---

bioconda_utils/utils.py
test/test_utils.py

This should fix some issues like in #505 where people get errors like:
23:52:01 BIOCONDA ERROR STDOUT+STDERR:
```
Traceback (most recent call last):
File "/opt/conda/lib/python3.6/site-packages/conda/cli/main.py", line 138, in main
return activator_main()
File "/opt/conda/lib/python3.6/site-packages/conda/activate.py", line 945, in main
print(activator.execute(), end='')
File "/opt/conda/lib/python3.6/site-packages/conda/activate.py", line 177, in execute
return getattr(self, self.command)()
File "/opt/conda/lib/python3.6/site-packages/conda/activate.py", line 154, in activate
builder_result = self.build_activate(self.env_name_or_prefix)
File "/opt/conda/lib/python3.6/site-packages/conda/activate.py", line 279, in build_activate
return self._build_activate_stack(env_name_or_prefix, False) …
```

Don't pass in CONDA_* env variables, they break conda 4.6

---

.circleci/config.yml
test/test_utils.py

Hope this works. Right now, we run hours of testing for every line in the docs.
Perhaps we should eventually split the docs out into a separate repo. We have three parts:
- written documentation on Bioconda
- package index and recipe docs
- bioconda_utils docs
(Cross referencing would still be possible via intersphinx).

Skip tests if only files in docs modified

---

MulledDockerfile
bioconda_utils/pkg_test.py

This won't pass testing until the container is actually uploaded of course. `MulledDockerfile` is an updated version of `continuumio/miniconda3` with a new conda inside. This container fixes issues like https://github.com/bioconda/bioconda-recipes/pull/14472 locally for me at least (I can reproduce those issues locally with the default `continuumio/miniconda3` container).

Create our own container for mulled testing.

---

bioconda_utils/bioconda_utils-conda_build_config.yaml

2.4.1 was built with the old compilers, so everything that links against it can't get updated. The most recent version of bamtools we've built is 2.5.1, so I suggest pinning to that instead.

Update bamtools pinning to a version that's been rebuilt

---

docs/source/guidelines.rst

This updates the "Name collisions" section of the guidelines to remove references to a now-removed "wget" package, replacing it with the secondary example, weblogo.

Update "Name collisions" section of guidelines

---

.circleci/build-docs.sh
bioconda_utils/autobump.py
bioconda_utils/cli.py
bioconda_utils/recipe.py

- CLI: disable fetching pypi requirements by default. It runs unknown code (setup.py), and should be explicitly enabled if desired.
- Janitoring: Remove `recipe.Recipe.config` which was just the `autobump.config`.
- Docs: actually use the variable pointing to master branch

Autobump updates

---

bioconda_utils/cli.py
bioconda_utils/cran_skeleton.py
bioconda_utils/docker_utils.py
bioconda_utils/utils.py
test/test_utils.py

- Adds three options to all commands that support `--loglevel`:
- `--logfile`: If given, output is also logged to this file
- `--logfile-level`: Specify logging level for logfile. Default is DEBUG
- `--log-command-max-lines`: If specified, *console* logging output from `utils.run` will be    truncated after *n* consecutive lines.
- Logs stdout/err live as `(ERR) msg` and `(OUT)` 
- Disables `tmp-bioconda-builder` unless explicitly requested via `--build-image`
This replaces #167

Add realtime command log output (with max) and log file

---

bioconda_utils/bioconductor_skeleton.py
test/test_bioconductor_skeleton.py

This should close #525. This issue has only hit us since we in to double digit minor release versions of bioconductor now, but '3.10' should be sorted before '3.9' when we get the list of releases.

Properly sort semantic versions of bioconductor and change cargoport interaction

---

docs/source/guidelines.rst

This PR adds a little note as to which python packages can be automatically created using `conda skeleton pypi`. 
I got bit by this myself ;-).

Conda skeleton pypi clarification

---

.circleci/config.yml
Dockerfile
bioconda_utils/bioconda_utils-requirements.txt

cf. https://gitter.im/bioconda/Lobby?at=5d1bb2d06933ed1a622a334a ff.
> That `Collecting package metadata (repodata.json)` looks like a change in `conda >=4.7.0` https://github.com/conda/conda/commit/1f2a1864199f35aefaade1ed1b8fe6333a73c8b5#diff-127bca0abbd39d90577af817c26af378R234 . But aren't we get conda `4.6.12` here, c.f., https://github.com/bioconda/bioconda-utils/blob/5ca450f4bc9462ca2472389aac000d96846e773b/bioconda_utils/bioconda_utils-requirements.txt#L3 ??
> Oh dear...
> ```
> >  docker pull bioconda/bioconda-utils-build-env &&  docker run --rm -it bioconda/bioconda-utils-build-env conda --version
> Using default tag: latest
> latest: Pulling from bioconda/bioconda-utils-build-env
> Digest: sha256:1bc2f91ac938dfb50283b77512ece61d4faaa9ef85a809c53095097e7c2f3b0a
> Status: Image …
```

Dockerfile: set auto_update_conda=False to allow conda=4.7.5 to downgrade itself

---

docs/source/user/install.rst

Linux install script was showing the command for Mac OS installation.

Docs: Wrong installation command for Linux

---

bioconda_utils/bioconda_utils-conda_build_config.yaml
bioconda_utils/utils.py
test/test_utils.py

Fixes https://github.com/bioconda/bioconda-recipes/pull/16402#issuecomment-511840128
```
```
Also fixes https://github.com/bioconda/bioconda-utils/issues/325 .

conda_build_config: clear CONDA_BUILD_SYSROOT and use exclusive_config_files

---

bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/build.py
bioconda_utils/utils.py

Couple of small fixes.
Update to `conda-build=3.18.9` to get https://github.com/conda/conda-build/pull/3621 in. (`run_exports`-related, see https://github.com/conda/conda-build/issues/3617 and linked issues for details)

Some fixes ( <-- most original/descriptive title... )

---

.github/workflows/GithubActionTests.yml
bioconda_utils/build.py
bioconda_utils/cli.py

Currently, when `bioconda-utils build` does not complete successfully, the work directory created in ${CONDA_PREFIX}/conda-bld is still removed, which can hinder debugging (e.g., any config.log gets removed). 
It would be helpful to have an option like `conda build --keep-old-work`; this PR (I think) roughly implements similar behavior for `bioconda-utils build` (but if there are differences in behavior, it would be OK to rename the option avoid confusion).

Add --keep-old-work option to keep work directory

---

docs/source/user/install.rst

fix link to badge-generator, though the static files should be moved below `user/`

fix link to badge-generator

---

Dockerfile

I am encountering issues that are detailed in #505. I believe this change fixes that.
Currently git is not on the path inside the container because Conda's base environment isn't activated when the container runs.

add conda base environment to path in dockerfile

---

bioconda_utils/build.py
bioconda_utils/cli.py
test/test_utils.py

This will eventually enable having more than one `bioconda-utils build` instance running at the same time. The basic idea is to partition the DAG on the root nodes into non-overlapping chunks. Workers can then process every Nth partition. The primary (sole?) conceived use of this is on the bulk branch.

Parallel builds

---

docs/source/contributor/guidelines.rst

To enforce python 3.6 or 3.7 this should probably be `>=3.6`

Fixing python version number

---

bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/lint/check_deprecation.py
docs/source/contributor/linting.rst
test/lint_cases.yaml

See bioconda/bioconda-recipes#19996
In short: `matplotlib` should almost never be a dependency in a recipe, and `matplotlib-base` should be used instead.

Add a uses_matplotlib linter check

---

.circleci/config.yml
.github/workflows/GithubActionTests.yml
Dockerfile.test
bioconda_utils/bioconductor_skeleton.py
bioconda_utils/build.py
bioconda_utils/cran_skeleton.py
bioconda_utils/docker_utils.py
test/conftest.py
test/test_utils.py

From conda>=4.4 on, conda is not restricted to root/base env anymore.
xref: https://github.com/bioconda/bioconda-recipes/pull/19402#issuecomment-567912780

build_recipes: enable container tests for conda-dependent recipes

---

bioconda_utils/bioconda_utils-requirements.txt

Older `gitpython` builds are broken when a newer `gitdb2` is installed.
See https://github.com/conda-forge/staged-recipes/issues/10874 and the linked issues therein for details.

requirements: update gitpython>=3.0.8,3.0.*

---

bioconda_utils/bioconda_utils-requirements.txt

This can wait for conda-build 3.19.0 to get tagged. It should apparently fix the currently broken `noarch: python` builds.

Bump conda-build requirement

---

docs/source/user/install.rst

See issue #643 - For consistency, change also the instructions for Linux.

 Installation for MacOS: use curl instead of wget

---

bioconda_utils/lint/check_deprecation.py

With severity set to only 'warning', the linter check is ineffective
because the CI run is marked as passing. And if there’s a green check mark
in the GitHub UI, there’s no reason to check the CI logs, which is the only
place the warning appears.

Use normal severity for uses_matplotlib lint

---

bioconda_utils/bioconda_utils-requirements.txt

ref: https://github.com/conda-forge/conda-build-feedstock/pull/131
Fixes the shebang replace issues from the PRs which are mentioned in the above reference.

requirements: revert to (patched) conda-build=3.18.12

---

bioconda_utils/bioconda_utils-conda_build_config.yaml
bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/bioconductor_skeleton.py

The skeleton updates should add blas and lapack as host dependencies for all compiled packages. This should prevent a repeat of the last "can't link to libopenblasp" errors that kept popping up on OSX.

Update bioconductor skeleton and pinnings

---

docs/source/contributor/guidelines.rst

The URL we point to in the official conda docs as reference for linking scripts was broken. This updates it to a working address.

fix broken url for conda link scripts

---

.circleci/setup.sh
Dockerfile
MulledDockerfile
Mulled_entrypoint
app/Dockerfile.web
bioconda_utils/bioconda_utils-conda_build_config.yaml
bioconda_utils/bioconda_utils-requirements.txt
test/test_bioconductor_skeleton.py

This updates our requirement to `conda=4.8.3`... and removes `current_repodata.json` from the config where possible.
We also have to adjust https://github.com/bioconda/bioconda-recipes/blob/8b019e7be9dbc87b3419f93b5a2afcf6a1411466/.circleci/setup.sh#L77 then. (And things for `bulk`.)

requirements: update to conda=4.8.3 + conda-build issue 3974 workaround

---

bioconda_utils/utils.py

IDK why, but for some reason `conda>=4.7.0` initializes its custom logging although it is not supposed to when run "via API".
refs:
- https://github.com/conda/conda/blob/b7bd38660104973da7900d0eb09fb326fb998c0d/conda/core/index.py#L52
- https://github.com/conda/conda/blob/b7bd38660104973da7900d0eb09fb326fb998c0d/conda/gateways/logging.py#L157-L159
Reported in https://github.com/bioconda/bioconda-recipes/pull/22854.
This PR adds a simple workaround.
"It ain't pretty, but functional."

logging: Add workaround for conda>=4.7.0 custom logging

---

bioconda_utils/bioconda_utils-conda_build_config.yaml
bioconda_utils/bioconda_utils-requirements.txt
docs/source/user/index.rst
docs/source/user/versions.rst

I added a package to Bioconda, and then flailed for quite a while not understanding why it wouldn't build against python=3.5 or python=3.8. If these are not supported, somewhere in the docs should say so. With this change, that's now true, and there's now a place to list similar information for other important software (maybe R?).

Add Docs: Only support python v3.6 and v3.7

---

bioconda_utils/bioconda_utils-conda_build_config.yaml
bioconda_utils/cli.py
bioconda_utils/update_pinnings.py

Some fixes for `update-pinnings`.
IMPORTANT: The change from https://github.com/bioconda/bioconda-utils/pull/662/files#diff-2aed786d397cbb062fb58d1ff86a6950R26 caused different build strings for `r-base`-dependent packages because it triggered the logic from https://github.com/conda/conda-build/pull/3895. I hadn't thought of that before unfortunately.
Thankfully the last Bioconductor `bulk` work happened before that change. That means it should not affect terribly many recipes.

update-pinnings fixes

---

bioconda_utils/utils.py
test/conftest.py
test/lint_cases.yaml

Fixes issue reported in https://github.com/bioconda/bioconda-recipes/pull/22992, i.e.,
recipe file ending with `.yml` instead of `.yaml` but not being detected by the linter.

lint: add trigger for missing_meta_yaml

---

bioconda_utils/build.py

Bulk builds fail completely due to https://github.com/conda/conda-build/pull/4001 .
Even with that patch (submitted as https://github.com/conda-forge/conda-build-feedstock/pull/140 too), we have to catch `DependencyNeedsBuildingError`.

build: catch both UnsatisfiableError, DependencyNeedsBuildingError

---

bioconda_utils/utils.py

We skip `noarch` packages on macOS CI in any case. So we can also skip finalizing the recipe since `build/noarch` should always be set, finalized or not.
This fixes (rarely happening -- I didn't note down the issue in which I noticed it, unfortunately) `bulk` run failures on `osx` due to https://github.com/bioconda/bioconda-utils/pull/670 if there is a `noarch` recipe that has satisfiable build requirements on Linux but not on macOS.

utils.get_package_paths: skip finalize for noarch on osx CI

---

docs/source/user/versions.rst

Fix wording based on feedback from @mbargull on the [initial PR](https://github.com/bioconda/bioconda-utils/pull/664) for this page. Been meaning to do this for a while, just got around to it. This simplifies the unsupported versions section - it just points people to the gitter instead of trying to triage possible outcomes here.

Update versions doc wording per feedback

---

bioconda_utils/utils.py

follow up fix for gh-668 that let's the `autobump` not process `bioconductor-*` recipes.

utils.get_recipes: consider exclude in meta_yaml_found handling

---

bioconda_utils/autobump.py
bioconda_utils/bioconda_utils-conda_build_config.yaml
bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/cli.py
bioconda_utils/graph.py
bioconda_utils/recipe.py
bioconda_utils/update_pinnings.py

Fixes/updates to `bioconda-utils update-pinning` and pinning updates to include Python 3.8 in our build matrix.

Update pinning: py3.8, conda-forge-pinning=2020.08.29.21.09.48

---

.circleci/config.yml
.github/workflows/GithubActionTests.yml
Dockerfile.test
bioconda_utils/docker_utils.py
docs/source/contributor/build-system.rst
docs/source/contributor/building-locally.rst
test/test_utils.py

This now no longer uses :latest, but rather whatever its version is when pulling the docker build container.

Ensure bioconda-utils uses the same version build container

---

.circleci/config.yml
.github/workflows/GithubActionTests.yml
.github/workflows/build-and-push-image.yml
Dockerfile
Dockerfile.test
bioconda_utils/build.py
bioconda_utils/docker_utils.py
bioconda_utils/involucro
bioconda_utils/pkg_test.py
docker-entrypoint
docker-entrypoint-source
docs/source/contributor/build-system.rst
test/test_case.yaml
test/test_pkg_test.py
test/test_utils.py

1. Use condaforge/linux-anvil-cos7-x86_64 as build base
- Update the build base system to Centos 7.
- Use the "conda" user from the conda-forge base image during build.
Write access to /opt/conda is given to "conda" via a group "lucky".
-> Make sure to `chgrp` (change group) and `chmod g=u` (copy (root)
users' permission to group) when changing /opt/conda in the image!
- Add back libGL.so.1 to the build container.
So it can be used for linking as well as non-container-based tests.
2. Use new base images and env creation container
Base images are:
- standard: quay.io/bioconda/base-glibc-busybox-bash:2.0.0 ~~1.1.0~~
- extended: quay.io/bioconda/base-glibc-debian-bash:2.0.0 ~~1.1.0~~
Container for environment creation via mulled:
- quay.io/bioconda/create-env
In conjunction with the …

Update to linux-anvil-cos7-x86_64 build base and new base container images

---

MANIFEST.in
bioconda_utils/pkg_test.py

Small fix for environment activation in the containers.
I tried out `quay.io/biocontainers/bowtie2:2.4.2--py39hc9c6fcd_2` and noticed the activation script was empty.
What happened was that the wrapper which instructs the activation script to be built wasn't included in the sdist/wheel and as such `mulled-build` downloaded `involucro` by itself. I.e., the built container image is fine, just didn't include the activation script (as all older images do anyway).

Fix involucro wrapper missing in sdist/wheel

---

Dockerfile

Also split the `yum install` into two commands since a sole non-existing package will cause a failure then atleast.

Fix ssh not being available in build container

---

bioconda_utils/pkg_test.py

Small fix regarding license copying into the containers.
`bioconda/create-env:2.0.0` used `cp -l` for licenses which does not work for bind mounted volumes like we use via mulled.
`bioconda/create-env:2.1.0` drops the `-l` and just copies the license files.
Plus, with `2.0.0` errors during those copying were not caught properly, i.e., copying failed because of the hard-linking issue but the build only logged this, but did not fail as intended.

Fix licenses copying for Biocontainers

---

bioconda_utils/pkg_test.py

In gh-707 I added `'. /usr/local/env-activate.sh'` to the tests. Mulled runs the test via `sh -c VAR.TEST` and as such uses `sh` which is `dash` in the extended base container, causing activation scripts with Bashisms to fail the test.

Ensure mulled tests run Bash (for activate script)

---

bioconda_utils/bioconda_utils-conda_build_config.yaml

This can be overridden in recipes' conda_build_config.yaml files.
(We have ensure that no MACOSX_DEPLOYMENT_TARGET env var is set
beforehand for this to work since conda-build prioritizes the env var.)
fixes gh-688

Set a default MACOSX_DEPLOYMENT_TARGET

---

.circleci/config.yml
docs/source/templates/package_dashboard.html

This PR reduces loading times for the package dashboard by changing the source of the plot data from [bioconda/bioconda-stats](https://github.com/bioconda/bioconda-stats) to [bioconda/bioconda-plots](https://github.com/bioconda/bioconda-plots). It also adds a new plot to each package that plots its total downloads over the cdf of all packages.

Add cdf plot and change plot source to bioconda/bioconda-plots

---

bioconda_utils/bioconda_utils-requirements.txt

With that tight 2.14 pin we get an old openssl=1.0.2u in the build
container which leads to some certificate issues for HTTPS connections.

requirements: Loosen git=2.14.* pin

---

bioconda_utils/lint/check_policy.py
docs/source/contributor/linting.rst
test/lint_cases.yaml

See https://github.com/bioconda/bioconda-recipes/issues/19456
Since that issue has been opened, a couple more recipes have been added with the version number prefixed by `v`. This lint should prevent that.
Initially I thought this should go into `check_syntax` section, but since that’s only about the `extra` section, I ended up choosing `policy`, not sure if that is the best fit.
Ping @wholtz

Add lint: check whether version starts with v

---

bioconda_utils/bioconda_utils-conda_build_config.yaml
bioconda_utils/bioconda_utils-requirements.txt

Update htslib pinning to 1.14, libdeflate to 1.9 and conda-forge-pinning to something from today.

conda-forge-pinning, htslib and libdeflate updates

---

bioconda_utils/docker_utils.py

Additionally reindex after build. Copying is not enough.
As discussed on gitter.

fix: allow pkg_dir to be empty by creating a real conda channel there

---

bioconda_utils/bioconda_utils-requirements.txt

As per pallets/markupsafe#282 / pallets/markupsafe#283 markupsafe v2.1 breaks Jinja2 < 3.0, which causes problems like https://github.com/bioconda/bioconda-recipes/pull/33263

fix: avoid latest markupsafe if using old jinja

---

.circleci/config.yml
.github/workflows/build-image.yml
Dockerfile
bioconda_utils/bioconda_utils-requirements.txt
docs/source/contributor/build-system.rst
docs/source/contributor/building-locally.rst

As mentioned by @DrYak in #736 , we need to update the local build instructions.
We could also add `conda mambabuild` instructions, which are handy for when you need to debug environment resolution issues.

feat: update conda pinnings and build docs (xref #736)

---

bioconda_utils/bioconda_utils-requirements.txt

Fix things like https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=12373&view=logs&jobId=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572

fix: Update to the most recent conda-build so git_url works again

---

bioconda_utils/bioconda_utils-conda_build_config.yaml

HTSlib 1.15 was released on Monday.
Samtools and bcftools users will expect samtools and bcftools to be built against htslib-1.15 (at present they have been built against 1.14 — it's surprising that this has worked; usually new samtools and bcftools releases require new htslib API functions, so such a build fails).
To avoid issues such as bioconda/bioconda-recipes#30296 and to avoid having non-sam/bcftools packages depend on outdated versions of htslib, we should bump the HTSlib pinning when new HTSlib releases come out.
This PR does that bumping for HTSlib 1.15. If this approach is accepted, when a new bioconda-utils is available, we can rebuild all htslib-requiring bioconda packages (including samtools and bcftools) with the new htslib release.

fix: Update htslib pinning to 1.15

---

bioconda_utils/graph.py

If we add stuff in run-time requirements they end up getting ignored when making the dependency graph. That can lead to some "fun" out of order failures for PRs with multiple packages.
Xref: https://github.com/bioconda/bioconda-recipes/pull/33805

fix: The dependency graph should use the run-time requirements too!

---

docs/source/contributor/setup.rst

Since GitHub has removed password authentication, using https will prompt users to use their password and get errors. I'd suggest switching to ssh to avoid this confusion and a headache for users to figure things out; this change will automatically solve the issue for users with ssh authentication already setup.

fix: https prompts to password, ssh to the rescue

---

bioconda_utils/utils.py

`bioconda_utils.utils.setup_logger()` adds a StreamHandler to the root logger. In the current setup, the original StreamHandler is left around, duplicating each message. This PR solves logging duplication caused by bioconda-utils. 
before:
```
INFO:bioconda_utils.cli:Considering total of 8389 recipes.
15:45:45 BIOCONDA INFO Considering total of 8389 recipes.
```
after:
```
15:46:04 BIOCONDA INFO Considering total of 8389 recipes.
```
note: conda_build _also_ causes logging duplication, but those cannot be fixed externally (`conda_build.utils.get_logger()` resets its logger every time it is called, and it's called everywhere)

fix: duplicate logging

---

MulledDockerfile

The libmamba solver [may not be quite ready yet](https://github.com/conda/conda/labels/solver%3A%3Alibmamba), and I guess mamba would have been used already if it was possible. But why not match the conda version to the one in the requirements? At worst there's no more version differences, at best there are improvements in speed or memory usage.
I'm hoping this is a step in countering the root causes to #68, #660 and [recipes #33415](https://github.com/bioconda/bioconda-recipes/issues/33415)

feat: update mulled-test conda to 4.12

---

docs/source/contributor/guidelines.rst

conda skeleton pypi reportedly does not work for many people at the moment. Several tutorials have switched to mentioning grayskull instead (which currently only works for pypi packages). guidelines.rst was updated to reflect this.

docs: update guidelines.rst to mention grayskull

---

bioconda_utils/utils.py

lstrip treats the argument as SET of characters to trim.
With the default of "recipes/" it would cut all the recipes that start with "r", "e", .. or "/".

fix: wrong usage of lstrip in ellipsize_recipes

---

.circleci/config.yml
README.md
bioconda_utils/bioconda_utils-conda_build_config.yaml

The intent here is to update pinnings to python 3.10, but only to be used on the bulk branch to rebuild packages as needed.
The specific steps involved here are:
- include python 3.10 in the pinnings (this PR)
- cut a new bioconda-utils release (when the Release Please PR is merged)
- let autobump bot pick up the new release
- merge the updated package PR in bioconda-recipes
- update common.sh (to point to newly-created bioconda-utils version) *but only in the bulk branch of bioconda-common*. The bulk branch of bioconda-recipes will read from the bulk branch of bioconda-common.

chore!: update pinnings to python 3.10

---

bioconda_utils/lint/check_syntax.py
test/lint_cases.yaml

Identify missing whitespace between a package and its version constraints, before it causes a cryptic error in the build phase.
Also implements the `fix` method, and adds lint test cases.
notes: `check_recipe` was used instread of `check_deps` because the latter removes version constraints.
resolves #789

feat: linter for missing space in dependency version contraints

---

.circleci/config.yml
.github/workflows/GithubActionTests.yml
.github/workflows/docs.yml
bioconda_utils/__init__.py
docs/source/_ext/bioconda_sphinx_ext.py
docs/source/contributor/linting.rst

Consolidating the documentation-building to a single location (GitHub Actions) rather than the current case of on CircleCI when scheduled but GH on push to master.
This also fixes a deprecation error in the recent distutils version used here that was otherwise preventing docs from being generated, and adds previously missing docs for the new version whitespace lint.

feat: schedule docs on GitHub actions

---

bioconda_utils/bioconductor_skeleton.py

The packages have been largely fixed in https://github.com/bioconda/bioconda-recipes/tree/bulk-bioconductor-data, but this way new packages will also have `-L`.

fix: add -L to curl commands used in bioconductor data pkgs

---

.github/workflows/GithubActionTests.yml
bioconda_utils/bioconda_utils-conda_build_config.yaml
bioconda_utils/bioconda_utils-requirements.txt

Pin htslib 1.16, which was released in mid August. Updating this pinning (and deploying the resulting bioconda-utils release and rebuilding htslib) is a prerequisite for releasing new samtools (cf bioconda/bioconda-recipes#36525) and bcftools (cf bioconda/bioconda-recipes#36524) packages.
Update conda-forge-pinning to the most recent release; in particular, so that libdeflate (used by htslib) is pinned to 1.13, as per recent conda-forge packages. Currently we pin libdeflate 1.10, which will surely soon drop out of _conda-forge/current_repodata.json_ which would result in a resurgence of bioconda/bioconda-recipes#24199.

feat: Update htslib and conda-forge pinnings

---

.circleci/config.yml

I had previously noticed some packages confusingly being built for py310 even though the only place we *should* have been building for py310 was on bulk. Figured something was pulling in conda-forge-pinnings maybe as part of an install process. But I just noticed https://github.com/bioconda/bioconda-recipes/pull/36889, which is the autobump bot picking up that we had updated pinnings...something that only happened recently in the master branch of bioconda-utils.
Turns out the autobump bot, which runs on CircleCI, was installing bioconda-utils straight from the master branch. This PR fixes it to use the method used everywhere else, which is to install the version specified in bioconda-common/common.sh.
This affected autobumped recipes where the autobump was successful and the PR was …

fix: autobump uses correct version from common.sh

---

.circleci/config.yml
bioconda_utils/bioconda_utils-requirements.txt

autobump fails since a couple of days, with to this error in the setup dependencies step:
```
Preparing transaction: - \ | / - \ done
Verifying transaction: / - \ | / - \ | / - \ | / - done
Executing transaction: | / - \ | / - b''
\ | b''
/ - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - done
Traceback (most recent call last):
File "/home/circleci/project/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
return func(*args, **kwargs)
File "/home/circleci/project/miniconda/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
exit_code = do_call(args, p)
File …
```

fix: use mambaforge for autobump jobs

---

bioconda_utils/involucro
bioconda_utils/pkg_test.py

~~With this little shell injection we can force `mulled-build` to invoke `mamba install` in place of `conda install`.
(It abuses the fact that `--conda-version` invokes a `conda install conda={conda_version}` in which we interject a `conda`->`mamba` aliasing right before the actual `conda install` for the target packages.)
This should only be taken as a possible temporary workaround that works with our current `galaxy-lib` dependency.~~
This now uses the existing `involucro` wrapper to inject a `conda`->`mamba` alias so `mamba install` is used in the container builds.
@dpryan79 suggested we could also add https://github.com/galaxyproject/galaxy/pull/14770 (via https://github.com/johanneskoester/galaxy-lib/tree/feat/use-mamba ) as a patch to …

fix: Use mamba in mulled-build

---

bioconda_utils/involucro
bioconda_utils/pkg_test.py
test/test_pkg_test.py

Use `quay.io/bioconda/create-env:latest` and ensure that we have updated `conda`/`mamba` packages installed.
This fixes the current state where we use `quay.io/bioconda/create-env:2.1.0` which was build 1 1/2 years ago and thus has a quite outdated `mamba` installed.

fix: Use newer mulled conda image

---

.github/quay-namespace-info.py
.github/workflows/changevisibility.yml

This PR adds a script to set private repos on Biocontainers to public. Using the Quay API, it will get all repos under `biocontainers`, and if private it will submit a `changevisibilty` API request for that repo.
A few files (info about each repo, and any repos that were set public) are kept as artifacts and deleted after 7 days.
An example usage is available here: https://gist.github.com/rpetit3/c1962790dee7fa513722eb575c348622?permalink_comment_id=4448741#gistcomment-4448741
Notes:
- Quay doesn't have a way to only get private repos, so each run pulls down all available repos (public and private)
- If needed we could integrate the script into `bioconda_utils`.

chore: add CI to changevisibility of private containers

---

docs/source/_ext/details_ext.py
docs/source/index.rst
docs/source/static/style.css
docs/source/templates/layout.html

This builds on ideas in @marcelm's #831 by keeping the front page streamlined while still supporting anchors that can be used as permalinks.
First, the `details_ext.py` Sphinx extension was updated to support adding an optional `:anchor:` argument. Using this option causes an anchor to be created at the top of the `<details>` element, which repeats the summary text followed by a `¶` with the permalink.
Then there's additional JS in the `docs/source/templates/layout.html` that, upon visiting an anchor, looks for the closest `<details>` to the target and makes it visible.
So once built, the link https://bioconda.github.io/index.html#do-not-modify-condarc will link to, and open if folded, the details section about how `-c bioconda` is not sufficient (the original inspiration for #831).

docs: support anchors in <details>

---

.github/workflows/build-image.yml
.github/workflows/release-please.yml
Dockerfile
bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/cli.py
bioconda_utils/docker_utils.py
bioconda_utils/utils.py

This PR try to add Linux aarch64/arm64 support for bioconda-utils:
- Support `BASE_IMAGE` build args in `Dockerfile`: the devs can specify `BASE_IMAGE` to switch base image.
- `bioconda_utils/bioconda_utils-requirements.txt`: Upgrade packages version to support Linux aarch64.
- Add `--docker-base-image` image to help users specify docker base image.
- Add Linux aarch64 image build to `release-please.yml` and `build-image.yml` workflow
- `bioconda_utils/docker_utils.py`: create conda build subdir according to arch.
After this PR, users can build the bioconda package by using same cmd with x86 by specifing `--docker-base-image` to build the  package. 
Note that the `mulled-test` are still not supported, there are a circle dependency between `bioconda-containers` and bioconda-utils, we'd …

feat: add Linux aarch64/arm64 support for bioconda-utils

---

bioconda_utils/hosters.py
test/test_bioconductor_skeleton.py

This is a first pass attempt at fixing #895.
Main changes are updating the GithubRelease hoster to look for alternate paths via the GitHub API.  The API sends a JSON response (example: https://api.github.com/repos/PacificBiosciences/HiPhase/releases) that contains each release along with a list of assets.  The assets are searched for files that match the provides pattern.  Currently, this first pass puts this as a backup to the main one (which I think is always failing now).  I also did not update the tests, I think someone may have a better idea of how to do that.  Happy to help push this further, but wanted to get the ball rolling.

fix: adds alternate lookup if base lookup fails

---

bioconda_utils/cli.py

In the https://github.com/bioconda/bioconda-utils/pull/866 we introduced the `--docker-base-image` to help user to specify customized build docker image (such as Linux aarch64 build).
But we noticed that it doesn’t work after the https://github.com/bioconda/bioconda-utils/pull/894 , because a local var introduced and the `docker-base-image` arguments is ignored.
This PR try to recover it, if user specify the `--docker-base-image`, it will be used directly otherwise use the local var.
Test:
```
[root@kunpeng bioconda-recipes]# bioconda-utils build --docker --packages bamstats --docker-base-image ghcr.io/yikun/bioconda-utils-build-env-cos7-aarch64
11:50:12 BIOCONDA INFO Considering total of 1 recipes (bamstats).
11:50:12 BIOCONDA INFO Processing 1 recipes (bamstats).
11:50:12 BIOCONDA …
```

fix: recover --docker-base-image feature

---

bioconda_utils/hosters.py

This is basically a patch to fix a new issue (described here: https://github.com/bioconda/bioconda-recipes/issues/42176) that was introduced by myself here: https://github.com/bioconda/bioconda-utils/pull/896.
The primary cause is that the GitHub API is rate limited (which I was not aware of), so autobump basically blows through the limits quickly and then subsequent calls automatically fail.  Of course, this means that the tools we were hoping to see get autobumped are not.
This patch basically removes the original patch (which uses a single GitHub API call) and replaces it with an approach that basically "expands" the release webpage to find the assets.  See https://github.com/bioconda/bioconda-utils/issues/895 for more details on how the URLs are masked and the expansion pattern. …

fix: swaps from github API to expanding the assets

---

bioconda_utils/build_failure.py

GitHub Action Update build Failure list (https://github.com/bioconda/bioconda-recipes/actions/workflows/build-failures.yml) is failing to find "r-boutroslabplottinggeneral" in the DAG because the recipe folder was being used instead of the name from meta.yaml.

fix: use package name instead of folder for build failure list dag check

---

bioconda_utils/bioconda_utils-conda_build_config.yaml

By patching repodata htslib dependencies, we no longer need to pin htslib. See bioconda/bioconda-recipes#42895.

fix: Remove htslib build pinning

---

bioconda_utils/lint/check_syntax.py
test/lint_cases.yaml

fix: Version constraints can start with `!` as well

---

.github/workflows/GithubActionTests.yml
.github/workflows/build-image.yml
.github/workflows/changevisibility.yml
.github/workflows/conventional-prs.yml
.github/workflows/release-please.yml

Currently Github Actions print warnings that the old plugins use unsupported version of Node.js (v12)

ci: Update the used Github Actions to their latest versions

---

bioconda_utils/artifacts.py
bioconda_utils/cli.py
bioconda_utils/utils.py

- Support for downloading artifacts from CircleCI instead of Azure.
- Added option `--artifact-source` with `choices=['azure', 'circleci']` to `handle_merged_pr`
- Check architecture when returning platform
- See PR for the ARM builds https://github.com/bioconda/bioconda-recipes/pull/40550

feat: download aarch64 artifacts from CircleCI

---

.github/workflows/GithubActionTests.yml
bioconda_utils/build.py
bioconda_utils/recipe.py
test/test_recipe.py
test/test_utils.py

This patches add support in bioconda-utils to run on linux-arm if the following is added to the recipe:
```yaml
extra:
additional-platforms:
- linux-aarch64
```
- Add a `check_native_platform_skippable` to checkout should we skip the recipes in current nativei platform
- Add `extra_additional_platforms` property to recipe object
- Add UT to test above function
```
py.test --durations=0 test/test_utils.py::test_native_platform_skipping
py.test --durations=0 test/test_recipe.py::test_recipe_extra_additional_platforms
```
- E2E test
```
bioconda-utils build recipes config.yml --git-range origin/master HEAD
bioconda-utils build recipes config.yml --git-range origin/master HEAD --force
```
- Fix test trigger by adding `fetch-depth`
related: …

feat: add support to run build for recipes with linux-aarch64 additional-platforms

---

.github/workflows/GithubActionTests.yml

The `Run tests` jobs were broken with https://github.com/bioconda/bioconda-utils/commit/1ae4126c5ba961667bc321c451957a50be305461 The problem is that the project uses `fetch-depth: 1` (the default) and thus has no branch history.
Refs:
- https://github.com/actions/checkout/issues/296
- https://github.com/actions/checkout/pull/301
Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

ci: Fetch the full Git history to be able to diff it against HEAD

---

bioconda_utils/build.py
bioconda_utils/cli.py
bioconda_utils/docker_utils.py

- Enable live logging except when a new `--disable-live-logs` option is enabled.
- This will improve troubleshooting of CI builds while having the option to avoid excessive log messages.

feat: Enable Live logs and add option to disable

---

bioconda_utils/lint/check_build_help.py

Closes typo noted on  https://github.com/bioconda/bioconda-recipes/issues/42660

docs: run_export -> run_exports plural in help message

---

bioconda_utils/build.py
bioconda_utils/pkg_test.py

Enable live logs for mulled-test.
The `--disable-live-logs` option was added in  https://github.com/bioconda/bioconda-utils/pull/930 but was only for the build. This will enable live logs for the mulled test.
Draft because it still needs testing.

feat: live logs for mulled build

---

bioconda_utils/upload.py

Port the fixes in f48280167a31cc87192e0a9ce729de935d702990, which were in `pkg_test.py`, to `upload.py` as well.
ping @bgruening this is what was causing that strangely different behavior in `mulled-build`'s `build-and-test` and `push` over in https://github.com/bioconda/bioconda-recipes/pull/43995.
After reviewing this and tracking down all the various moving parts, it's *really* unclear how the various docker images are specified throughout all our machinery. Explicit and implicit env vars set at various times, sometimes overridden by default args, sometimes not, sometimes hard-coded deep in bioconda-utils. Needs a refactor, where everything gets specified just once in bioconda-common and used everywhere. That's for another day though...

fix: specify involucro path when uploading

---

bioconda_utils/utils.py

Check if the GITHUB_TOKEN environment variable exists for getting the PR during artifact fetching. Since it's a read-only request, it works without a token. The risk is that GitHub API has a 60 request/hr limit for unauthenticated users associated with the originating IP address. https://docs.github.com/en/rest/overview/rate-limits-for-the-rest-api
We talked about adding a flag to specify not using the token, but I thought it would be cleaner to just log a warning and proceed. (Also open to adjusting the retry for the tokenless option, but usually a rate limit would be 429 return code and this retry policy is only for 500, 502, 504.)

feat: make GITHUB_TOKEN optional for fetch

---

bioconda_utils/docker_utils.py

The local folder channel was not included in the command, causing newly built packages on the `bulk` branch to not be usable to their descendants on the same worker because of strict channel priority.

fix: add local channel for docker builds

---

bioconda_utils/lint/check_build_help.py
test/lint_cases.yaml

The current lint is only happy with `compiler("c")`, but `compiler("cxx")` works just as well if the project is a C++ project. I noticed this in <https://github.com/bioconda/bioconda-recipes/pull/43724>.

fix: Do not emit cython_needs_compiler if compiler("cxx") is set

---

bioconda_utils/build_failure.py
bioconda_utils/cli.py
bioconda_utils/utils.py

In order to have a `bulk` branch-specific Build Failures wiki page, need to allow for a git range to be specified for which recipes will be included. This uses the same method of determining whether a recipe is included as the build command. (i.e., it's not diffing the build failure files between branches.)
Also added handling for recipes that exist but have no corresponding package in the channel. That avoids errors from new Bioconductor recipes during a bulk update.

feat: Bulk build failure wiki

---

bioconda_utils/bioconductor_skeleton.py
bioconda_utils/build_failure.py
bioconda_utils/bulk.py
bioconda_utils/cli.py

Some fixes identified when preparing for the Bioconductor 3.18 updates:
**run_exports.** `bioconductor-skeleton` now adds run_exports to the recipes it builds. Since it's unclear to what extent all bioconductor developers adhere to semantic versioning, I opted for `max_pin="x.x"`, even in the cases where versions start with `0.`.
**Better build numbers.** `bioconductor-skeleton update-all-packages` will now only modify the build number if it's needed. It checks what's available in the channel. So running the command multiple times (sometimes needed if the update process flakes out partway through) will not keep bumping the build number. This also uses the same check as the linting, which will hopefully reduce the frequency of build number adjustments in bulk.
**Fix manual build failure …

feat: bioconductor improvements

---

bioconda_utils/bioconda_utils-requirements.txt

beautifulsoup4 and requests need a version that is noarch. The older version of backoff was causing an error with asyncio on Mac.

chore: requirements updates needed for osx-arm64

---

bioconda_utils/build.py
bioconda_utils/utils.py
test/test_recipe.py
test/test_utils.py

add osx-arm64 to platforms and only build if additional platform is configured

feat: add osx-arm64 to platform checks

---

bioconda_utils/bioconda_utils-requirements.txt

I'll update other dependencies shortly.
Putting this in separately beforehand to fix current package upload problems for `bioconda-recipes`.

fix: update anaconda-client=1.12 to fix uploads

---

.github/workflows/GithubActionTests.yml
bioconda_utils/artifacts.py
bioconda_utils/cli.py

GitHub requires a token for artifact downloads from their API. (A logged-in user is required for the normal download link shown on the Actions page. This needs to be kept in mind when we update the download comment from the bot.)
I could not find any way to get the workflow run ID or artifacts from the check run object except parsing the URL.

feat: fetch artifacts from GitHub Actions

---

bioconda_utils/bioconda_utils-conda_build_config.yaml

11.0 is the oldest SDK that has arm64 support.

feat: update deployment target for osx-arm64

---

bioconda_utils/artifacts.py

This was erroring out on line 44 instead of returning on line 43 because the prs object existed, but had no items.

fix: handle PR list with no items

---

bioconda_utils/build.py
bioconda_utils/cli.py

In an attempt to try a more efficient process for doing bulk builds, I added an option `--subdag-depth` (int, default: None) that will only assign recipes with a certain dependency depth to the bulk workers. Only nodes of a certain depth will be built (i.e., 0: only root nodes, 1: only nodes with parents that are root nodes, etc.). The idea is to allow someone to build all recipes that have no dependencies in the DAG, then remove those from the DAG and build the new "root" recipes. The existing behavior will still work if `--subdag-depth` is not included.
Currently, manual intervention is needed to do the Bioconductor bulk update because the recipes are assigned unevenly to the workers and some child nodes are dependent on recipes being built on a different worker. This new approach also …

feat: choose worker recipes by depth level

---

.github/workflows/GithubActionTests.yml

GitHub Actions changes are being rolled out to change `macos-latest` to use `macos-14` which has ARM architecture. Specify `macos-13` to continue to test on x86-64.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

ci: specify macos version to control architecture

---

bioconda_utils/build.py
bioconda_utils/docker_utils.py
bioconda_utils/involucro
bioconda_utils/pkg_test.py
bioconda_utils/recipe.py
bioconda_utils/utils.py
test/test_pkg_test.py

conda>=23.10 uses conda-libmamba-solver by default which means we don't need the solver injection via boa/conda-mambabuild anymore since it is handled upstream.

feat: Use conda/conda-build instead of mamba/conda-mambabuild

---

bioconda_utils/artifacts.py

This is to fix bioconda/bioconda-recipes#47663 for fetching artifacts from a PR that was just merged to master in order to upload to the channel
We may want to follow it up with updates to use a token, but I wanted to get it to a working state for right now

fix: use circleci api v1.1 to avoid login error

---

bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/pkg_test.py
bioconda_utils/utils.py
test/test_utils.py

We used some custom code to extract test information from `.tar.bz2` packages which would need adjustments to handle `.conda` packages -- but nowadays we can just use `conda-package-streaming` for this instead, as done here.

fix: test_package for .tar.bz2 and .conda

---

MANIFEST.in
bioconda_utils/bioconda_utils-requirements-docs.txt
bioconda_utils/bioconda_utils-requirements.txt
setup.py

As of now, additional requirements for building docs add about 60 packages (+44MB downloaded, 290MB installed) not used by the build env.

chore!: Separate docs-only requirements

---

bioconda_utils/docker_utils.py
test/test_utils.py

This way we should be able to switch to `pkg_format: 2` (i.e., build `.conda` packages) via config from `bioconda-common`.

fix: Pass pkg_format to container-based build

---

bioconda_utils/build.py

New images use Debian 12.5 base and are built with Buildah >=1.35.0 for better compatibility w.r.t. gh-958 .
refs:
- https://github.com/bioconda/bioconda-containers/pull/82
fixes gh-958

feat: Update base-glibc-*-bash images to 3.1

---

bioconda_utils/bioconda_utils-conda_build_config.yaml
bioconda_utils/bioconda_utils-requirements.txt

Amongst others, this includes:
- Update default minimum system targets to
- `glibc 2.17`/CentOS 7 ( \*needs recipes to include new `- {{ stdlib("c") }}` dep in `requirements/build`)
- macOS 10.13
- Python 3.11 and 3.12
closes gh-938, gh-988

feat: Update pinning 2024-05

---

bioconda_utils/utils.py

When running bulk for linux-aarch64 on CircleCI, all recipes started building, even ones that had not been bumped. The `FILTER: not building recipe X because the same number of builds are in channel(s) and it is not forced.` message was not present in the log. This is because one place in bioconda-utils was missed when adding`linux-aarch64`. 
Bioconda-utils gets a dataframe of packages from the bioconda and conda-forge channels and then compares with the list of recipes requested to be built to see if a build already exists for that subdir, version, build number, and build string. Only `linux-64`, `osx-64`, and `noarch` were being considered. (The platform here gets converted to a subdir string which has the `-64` suffix.)
After this is merged and released, I will re-enable bulk for …

fix: add missing Arm platforms to skip existing builds

---

bioconda_utils/artifacts.py

Although the endpoints to list workflow jobs and artifacts used to be accessible to anyone, now there is a 401 response code.
Previously we worked around this by changing the API version back to v1.1, but now it's happening again for both versions. This apparently happens often. https://discuss.circleci.com/t/api-token-needed-to-fetch-artifacts/50881/3 So, it makes sense to just use a token. I've configured this in CircleCI already.
(Another PR will be coming soon for the comment responder to fetch the artifacts.)

fix: token for CircleCI artifacts

---

.circleci/config.yml

CircleCI is removing the image: https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
This is the one we are using for linux-aarch64 builds.

ci: update autobump machine image

---

bioconda_utils/artifacts.py

GitHub Actions doesn't allow artifact files to contain `:`, so it is replaced with `---`. Update this artifact finding code to match that pattern.

fix: fix image artifact regex to match GitHub Actions filename

---

bioconda_utils/lint/check_build_help.py
test/lint_cases.yaml

Rust has been a supported compiler for a little while now, and with the [new guidelines for Rust recipes](https://bioconda.github.io/contributor/guidelines.html#rust), it would be good for the linting to help people

feat: add rust to should_use_compilers lint

---

bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/build.py
bioconda_utils/utils.py

To diagnose out of disk and out of memory errors, log free disk space and available memory before and after each recipe is built and each mulled test.

feat: report resource usage before and after builds

---

bioconda_utils/bioconductor_skeleton.py

- When running `bioconda-utils bioconductor-skeleton` on Bioconductor data packages, I was getting self-signed SSL errors (@bgruening is this expected?). This change allow such errors to be ignored, returning None for the url.
- In this round of Bioconductor 3.20 updates, it seems like a lot of packages are now missing `zlib`. I still haven't pinpointed the reason, but I'm guessing it has something to do with the updates to pinnings. So for BioC packages that are detected to be compiled, this adds `zlib` to host dependencies.

feat: Bioconductor skeleton updates

---

bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/bioconductor_skeleton.py

During BioC 3.20 builds, many pkgs were missing zlib and liblzma.
This PR also updates aiohttp to address dependabot alerts.

feat: add liblzma-devel to host deps for compiled bioc pkgs

---

bioconda_utils/bioconductor_skeleton.py

Looks like we don't need the `.decode('utf8')` anymore; this line was originally added in 2017 so it was probably using py27 or something at the time.

fix: don't decode

---

bioconda_utils/lint/check_syntax.py

See conda package match specifications:
https://docs.conda.io/projects/conda-build/en/25.1.x/resources/package-spec.html#package-match-specifications
This syntax has also been around for a bit, I can already see it in the `24.1.x` docs.

fix: allow tilde in conda version constraints

---

bioconda_utils/hosters.py

Adding `pypi.org/packages` to the hoster_pattern for PyPi (which is a redirection to `files.pythonhosted.org/packages`), which I believe is the URL that e.g. grayskull uses.

fix: include pypi.org/packages in PyPi hoster_pattern

---

.github/workflows/changevisibility.yml

I believe this should fix https://github.com/bioconda/bioconda-recipes/issues/54470

ci: update upload-artifact version in changevisibility since v3 was removed

---

.github/workflows/build-image.yml
.github/workflows/release-please.yml

ubuntu-20.04 is no longer supported
set-output is deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: update image workflow to use ubuntu-24.04, remove deprecated set-output

---

bioconda_utils/recipe.py

The recipe `ligand-validation` was added with an empty `extra:` section in meta.yaml. This will handle that situation without throwing an error during the nightly ARM builds.

fix: handle recipes with an empty extra section
