bioconda/bioconda-utils

bioconda_utils/pkg_test.py
bioconda_utils/utils.py
test/test_utils.py

use channel order in mulled tests

Channel order

---

bioconda_utils/build.py
bioconda_utils/channel_order.txt
bioconda_utils/pkg_test.py
bioconda_utils/utils.py
setup.py
test/test_pkg_test.py
test/test_utils.py
travis-setup.sh

This PR hopefully fixes many of the channel order issues we've been having.
xrefs:
- https://github.com/bioconda/bioconda-recipes/pull/2892#issuecomment-260016776
- #31

assume channels are sorted from highest to lowest

---

bioconda_utils/build.py
bioconda_utils/pkg_test.py

This PR fixes the container tests and implements a feature for future automatic pushes to the biocontainers registry.
ping @daler

Container test and push improvements

---

docs/source/conf.py
docs/source/contrib-setup.rst
docs/source/contribute-a-recipe.rst
docs/source/guidelines.rst
docs/source/templates/layout.html

font tweaks; move content from bioconda-recipes/README; some cleanup and clarification.

docs edits

---

docs/source/guidelines.rst

added notice about java-jdk deprecation.
xref: https://github.com/bioconda/bioconda-recipes/pull/3364#issuecomment-270418475

added notice about openjdk

---

bioconda_utils/build.py
bioconda_utils/cli.py

xref https://github.com/bioconda/bioconda-recipes/issues/3271

send TRAVIS env vars to docker container

---

bioconda_utils/bioconda_utils-requirements.txt
docs/source/faqs.rst
docs/source/guidelines.rst

Still trying to solve the issue from bioconda/bioconda-recipes#3761.

Fix warnings in docs, pin sphinx and docutils to a working combination.

---

docs/source/contrib-setup.rst
docs/source/contribute-a-recipe.rst

Update docs as requested:
https://github.com/bioconda/bioconda-recipes/issues/3674

 update one-time setup

---

bioconda_utils/build.py
bioconda_utils/docker_utils.py
bioconda_utils/upload.py
bioconda_utils/utils.py

such that duplicate messages are avoided and hopefully the order becomes more clear.

Refactor handling of stdout and stderr

---

bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/build.py
bioconda_utils/cli.py
bioconda_utils/docker_utils.py
bioconda_utils/upload.py
bioconda_utils/utils.py
setup.py

This should further improve readability. Includes PR #79.

Colored logs and generalized logger setup.

---

docs/source/linting.rst
docs/source/troubleshooting.rst

mostly formatting; using a more uniform format for describing linting functions

Lint docs updates

---

bioconda_utils/build.py
bioconda_utils/cli.py
test/test_utils.py

This shall **not** be merged before bioconda/bioconda-recipes#4473.

[WIP] Add --anaconda-upload to the CLI for enabling uploads to Anaconda.

---

bioconda_utils/build.py
bioconda_utils/docker_utils.py
bioconda_utils/utils.py
setup.py

This is more compatible with CI consoles.

Print progress with dots instead of using a spinner.

---

bioconda_utils/build.py
bioconda_utils/pkg_test.py
bioconda_utils/utils.py
test/test_pkg_test.py

Before, I made an error when retrieving the image name from the recipe.

Fix custom container

---

bioconda_utils/cli.py

@bgruening @daler, this new subcommand allows us to detect duplicates between our channel and others.
Look at this list:
```
name	version	build	channels
aniso8601	1.1.0	py27_0	conda-forge
aniso8601	1.1.0	py34_0	conda-forge
aniso8601	1.1.0	py35_0	conda-forge
appdirs	1.4.0	py27_0	conda-forge
appdirs	1.4.0	py34_0	conda-forge
appdirs	1.4.0	py35_0	conda-forge
appdirs	1.4.0	py36_0	conda-forge
argh	0.26.2	py27_0	conda-forge
argh	0.26.2	py34_0	conda-forge
argh	0.26.2	py35_0	conda-forge
arrow	0.7.0	py27_0	conda-forge
arrow	0.7.0	py34_0	conda-forge
arrow	0.7.0	py35_0	conda-forge
bcdoc	0.16.0	py27_0	conda-forge
bcdoc	0.16.0	py34_0	conda-forge
bcdoc	0.16.0	py35_0	conda-forge
bcdoc	0.16.0	py36_0	conda-forge
blinker	1.4	py27_0	conda-forge
blinker	1.4	py34_0	conda-forge
blinker	1.4	py35_0	conda-forge …
```

Detect duplicates between bioconda and other channels.

---

docs/source/guidelines.rst
docs/source/index.rst

@bgruening anything you want to add to biocontainers info?

Docs update

---

bioconda_utils/lint_functions.py

xref https://github.com/bioconda/bioconda-recipes/issues/4976

disable noarch linting

---

bioconda_utils/lint_functions.py
bioconda_utils/linting.py
docs/source/linting.rst
test/test_linting.py

addresses #150, sorry @johanneskoester this is a little late for all your `vg` recipe commits!

Skip lints in extra

---

bioconda_utils/pkg_test.py

If I'm correct this should fix bioconda/bioconda-recipes#5174 , see also bioconda/bioconda-recipes#5131.

Should fix #5174

---

bioconda_utils/utils.py

specifically blacklist CONDA_PREFIX from docker envs

---

setup.py

remove install_requires; rely on conda to install deps

---

bioconda_utils/build.py
bioconda_utils/utils.py

xref https://github.com/bioconda/bioconda-recipes/issues/5461

exclude PATH when passing env to docker

---

bioconda_utils/cli.py
bioconda_utils/utils.py

@bgruening this should help with the r migration. 
Here are the results of:
```bash
bioconda-utils dag recipes/ config.yml --format txt --packages "r-*" \
| sed "/recipes/ s|recipes/|- [ ] |"
```
We can take chunks of 10 or so off the top and submit to conda-forge.

update dag cli

---

bioconda_utils/bioconductor_skeleton.py

Better support for older bioconductor versions; support for fixing https://github.com/bioconda/bioconda-recipes/pull/5864

Bioconductor skeleton fixes

---

bioconda_utils/cli.py
docs/source/contribute-a-recipe.rst
docs/source/guidelines.rst

xref https://github.com/bioconda/bioconda.github.io/pull/9

docs updates

---

bioconda_utils/bioconductor_skeleton.py

bioconductor annotation packages seem to have been working well; this PR adds support for data packages under the "experiment" namespace.

add support for bioconductor experiment data packages

---

docs/source/build-system.rst

xref https://github.com/bioconda/bioconda-recipes/issues/6812

add docs for bulk branch

---

docs/source/troubleshooting.rst

add docs for extended base

---

bioconda_utils/bioconductor_skeleton.py

discovered in https://github.com/bioconda/bioconda-recipes/pull/6916

Fallback url

---

docs/source/index.rst

update company name; make trademark info more prominent

update trademark info

---

bioconda_utils/cli.py

This should fix https://github.com/bioconda/bioconda-utils/commit/745adc08cae005a7e4798ba50d4752f5623aec6e#commitcomment-26715983 (ping @boll3).

remove no_windows from cli

---

bioconda_utils/lint_functions.py
test/test_linting.py

I think this is broken since https://github.com/bioconda/bioconda-utils/pull/191

fix liniting of pinnings

---

docs/source/contrib-setup.rst
docs/source/contributing.rst
docs/source/guidelines.rst

xref https://github.com/bioconda/bioconda-recipes/issues/7550

clarifications on circle ci setup

---

.circleci/build-docs.sh

follow-up on https://github.com/bioconda/bioconda-utils/pull/274

use two cores for sphinx

---

docs/source/conf.py
docs/source/generate_docs.py
docs/source/templates/readme.rst_t
docs/source/templates/recipes.rst_t

You guys merged too fast :)
- Fix parallel build
- Add doc_url and dev_url links (only showing doc_url if different from home)
- Document stuff & cleanup

More updates to docs

---

docs/source/guidelines.rst
docs/source/troubleshooting.rst

xref https://github.com/bioconda/bioconda-recipes/issues/8183

clarify patch policy

---

docs/source/contribute-a-recipe.rst

Adds a bit better documentation explaining reviewing mode:
https://github.com/bioconda/bioconda-recipes/issues/8267

Better documentation for reviewing

---

docs/source/guidelines.rst

I'm seeing this pop up a lot, figured it'd be useful to have a place in the docs to point to so I don't have to keep typing the same thing ;)

add note about conda-build 3 skeleton

---

docs/source/guidelines.rst

@bioconda/haskell : I decided to share some of the little tricks I learned while working on the ngless recipe yesterday, but maybe this should be a group effort and if you have other tips, add them here.

Add Haskell guidelines

---

.circleci/config.yml
README.md
bioconda_utils/lint_functions.py
docs/source/linting.rst
test/test_linting.py

Adds lint for BioC 3.7 (plus docs); xref https://github.com/bioconda/bioconda-recipes/issues/8947.

add linting for bioc 3.7

---

.circleci/config.yml
.circleci/setup.sh
bioconda_utils/pkg_test.py
bioconda_utils/utils.py
setup.cfg
test/test_utils.py

Cherry picked commits from gh-293 and a fix for gh-302.

build/test speedup and fix for #302

---

bioconda_utils/bioconductor_skeleton.py

Update bioconductor_skeleton to avoid error AttributeError: 'BioCProjectPage' object has no attribute 'url'
Example of package giving this error: bioconda-utils bioconductor-skeleton recipes config.yml FlowSorted.Blood.450k --pkg-version 1.16.0 --bioc-version 3.6
Traceback of the error:
Traceback (most recent call last):
File "/home/murilo/miniconda3/bin/bioconda-utils", line 11, in <module>
load_entry_point('bioconda-utils==0.12.2+84.gba7e0b9e.dirty', 'console_scripts', 'bioconda-utils')()
File "/home/murilo/miniconda3/lib/python3.6/site-packages/bioconda_utils-0.12.2+84.gba7e0b9e.dirty-py3.6.egg/bioconda_utils/cli.py", line 606, in main
argh.dispatch_commands([build, dag, dependent, lint, duplicates, bioconductor_skeleton, pypi_check, clean_cran_skeleton])
File …

Fix error 'BioCProjectPage' object has no attribute 'url'

---

.circleci/setup.sh
Dockerfile
README.md
bioconda_utils/example_config.yaml
bioconda_utils/pkg_test.py
docs/source/cb3.rst
docs/source/faqs.rst
docs/source/guidelines.rst
docs/source/index.rst
test/test_bioconductor_skeleton.py

xref: https://github.com/bioconda/bioconda-utils/issues/330

Use conda-forge with a higher priority than bioconda.

---

bioconda_utils/githubhandler.py
bioconda_utils/hosters.py
bioconda_utils/templates/bump_pr.md
bioconda_utils/update.py

Autobump: show/ping upstream authors for github hosted projects

---

bioconda_utils/cli.py
docs/source/generate_docs.py

- Don't require `GITHUB_TOKEN` if also `--dry-run` (unit tests from fork don't have access to token)

Fix tests failing from fork

---

docs/source/guidelines.rst

This originates from reviewing the contribution of a non-CRAN, non-bioconductor R-package to bioconda, that threw up some questions for me. @jdblischak kindly provided some insights:
https://github.com/bioconda/bioconda-recipes/pull/13410#issuecomment-458959377
I hereby suggest to add these and some further infos to the docs, and would be grateful for further review from the other @bioconda/r people.

docs: add r other sources guidelines

---

docs/source/generate_docs.py

Fix rendering bugs on docs

---

bioconda_utils/bioconductor_skeleton.py
test/test_bioconductor_skeleton.py

This fixes issue bioconda/bioconda-recipes#13846.

Use curl instead of wget for data packages.

---

docs/source/updating.rst

also fixed some Markdown->RST typos

Corrected pip install bioconda-utils instructions

---

.circleci/build-docs.sh
docs/README.md

We don't see issues posted over there, or people creating PRs against the computed `rst`s
Unless anyone objects, I will also disable issues and PRs on that repo once I've cleaned the existing items out.

Add README.md to bioconda.github.io

---

app/docker-compose.yml
bioconda_utils/bot/config.py
bioconda_utils/bot/views.py
bioconda_utils/bot/worker.py
bioconda_utils/utils.py

- add webhook secret (fixes #474)
- add timeout to repodata cache (fixes #475)

Bot updates

---

docs/source/guidelines.rst

noted in https://github.com/bioconda/bioconda-recipes/pull/15189#issuecomment-490566204 all CRAN packages should be deposited in conda-forge. This will save time for future contributors.

Point contributors to conda-forge for CRAN packages (for CRAN packages without Bioconductor Dependencies)

---

bioconda_utils/cli.py
bioconda_utils/recipe.py

Fix cli issue

---

bioconda_utils/bot/commands.py
bioconda_utils/bot/events.py
bioconda_utils/circleci.py
bioconda_utils/githubhandler.py

- `@biocondabot merge` now checks for required reviews correctly.
- The  "Packages built on CircleCI ready for inspection" message now generated for PRs from forks as well.

Bioconda bot updates

---

bioconda_utils/bot/commands.py
bioconda_utils/bot/tasks.py
bioconda_utils/bot/views.py
bioconda_utils/bot/worker.py
bioconda_utils/githandler.py
bioconda_utils/githubhandler.py

- hopefully fixes #576 
- some janitoring
- adds `@biocondabot update` which will trigger an update of PR branch to master

Bioconda bot

---

bioconda_utils/bioconda_utils-requirements.txt

These are the newest versions. I'm curious if this will pass testing even.

Update conda and conda-build

---

bioconda_utils/lint/check_build_help.py
docs/source/user/install.rst

Update some broken links and fix cython lint message

---

.circleci/config.yml
.github/workflows/GithubActionTests.yml
.github/workflows/test.yml
bioconda_utils/bioconda_utils-conda_build_config.yaml
bioconda_utils/bioconda_utils-requirements.txt
docs/source/contributor/guidelines.rst

This implements github actions for most of our CI testing.

try out some actions, update pinnings and fix some docs

---

.github/workflows/GithubActionTests.yml
Dockerfile
bioconda_utils/bioconductor_skeleton.py
bioconda_utils/cli.py
setup.py

This should do the following (mostly layed out in #588 ):

Update the bioconductor skeleton

---

bioconda_utils/lint/check_noarch.py
test/lint_cases.yaml

lint: fix: should_not_be_noarch_source triggered for noarch:False

---

.circleci/config.yml
.github/workflows/GithubActionTests.yml
setup.cfg
test/test_utils.py

Just to make the tests finish a bit faster.
Not very clever, I know.

Split off more long running tests

---

.circleci/config.yml

xref: https://github.com/bioconda/bioconda-recipes/pull/19518

ci: update circleci macos image to "xcode: 9.4.1"

---

Dockerfile
bioconda_utils/bioconda_utils-requirements.txt

This gives us https://github.com/conda/conda-build/pull/3897 which fixes failed builds like in https://github.com/bioconda/bioconda-recipes/pull/21011.

requirements: update to conda-build=3.19.1

---

.circleci/build-docs.sh
bioconda_utils/bioconda_utils-requirements.txt
bioconda_utils/sphinxext.py
docs/source/conf.py
docs/source/contributor/building-locally.rst
docs/source/contributor/faqs.rst
docs/source/contributor/guidelines.rst
docs/source/contributor/linting.rst
docs/source/contributor/troubleshooting.rst
docs/source/contributor/workflow.rst
docs/source/index.rst
docs/source/static/style.css
docs/source/templates/readme.rst_t

I'll post screenshots for comparison in a bit (building docs locally right now..).

docs: rename recipe index to package index + minor layout fixes

---

docs/source/contributor/faqs.rst

I did not find a direct link to https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html while trying to better understand meta.yaml and what it already can do out of the box. I hope this FAQ is helpful to others starting out.

Added FAQ on meta.yaml

---

docs/source/contributor/guidelines.rst
docs/source/contributor/troubleshooting.rst
docs/source/user/versions.rst

This is what @dpryan79 explained to me while I was trying to upload the TRTools package. Figure it would be useful to include in the docs for future contributors. I'm no expert on this, so please correct the wording where I'm misrepresenting some detail.

Add explanations on how to handle tests with dependencies

---

bioconda_utils/bot/tasks.py
bioconda_utils/build.py
bioconda_utils/templates/lint_failure.md

I noticed this today when one of my recipes failed a lint :sweat_smile:

update incorrect linting URL

---

docs/source/contributor/guidelines.rst

describe another supefluous section from cran skeleton that applies to [win]

improve cran skeleton docs

---

docs/source/contributor/guidelines.rst

This is follow up of https://github.com/bioconda/bioconda-utils/pull/685
Sorry for messing this up in the first place.

fix rst syntax

---

.dockerignore
.github/workflows/build-and-push-image.yml
Dockerfile
docker-entrypoint

Add GitHub Actions workflow to push container images to Quay.io for releases.

CI: Add quay.io/bioconda/bioconda-utils-build-env

---

bioconda_utils/autobump.py
bioconda_utils/cli.py
bioconda_utils/hosters.py

Fixes gh-701
+ two small bug fixes.

Fix autobump for changed GitHub tag archive URLs

---

bioconda_utils/bioconda_utils-requirements.txt

I should have done this in the last PR.

Update conda-forge-pinning requirement

---

bioconda_utils/templates/autobump_pr.md

Try to fix #730 cause I agree it'll be helpful.

Update autobump PR template

---

bioconda_utils/bioconda_utils-conda_build_config.yaml

I didn't use release please so there was no container produced for the last build :(

fix: missing container

---

bioconda_utils/bioconda_utils-requirements.txt

chore: let pyjwt version float

---

.github/workflows/docs.yml
docs/source/developer/index.rst

This PR documents the process of updating bioconda-utils, including the new Release Please workflow and getting it running in Azure DevOps.

docs: notes on updating bioconda-utils

---

docs/source/index.rst

docs: Add Robert A Petit III to the core team

---

.github/workflows/docs.yml

chore: change schedule for testing purposes

---

docs/source/developer/bulk.rst
docs/source/developer/index.rst

Initial draft of conventional commit guidelines and how to update pinnings on bulk.

docs: developer documentation updates

---

bioconda_utils/bioconductor_skeleton.py
bioconda_utils/cli.py

Xref: https://github.com/bioconda/bioconda-recipes/pull/37578

feat: switch data packages to bioconductor-data-packages

---

bioconda_utils/bioconda_utils-conda_build_config.yaml

feat: Update GLPK pin for BioC 3.16 bulk rebuild

---

docs/source/developer/bulk.rst

Updates based on the bioconda-core meeting today; @dpryan79 can you please review for accuracy/completeness?

docs: update bulk docs to include BioC updates

---

bioconda_utils/bioconda_utils-conda_build_config.yaml

As needed by:
- https://github.com/bioconda/bioconda-recipes/pull/39501 
-  https://github.com/bioconda/bioconda-recipes/pull/39499

build: update htslib version to 1.17

---

.circleci/config.yml

CircleCI config needs to be fixed to use new installation script

fix: fix autobump

---

.circleci/config.yml
.github/workflows/GithubActionTests.yml

This removes one of the last vestiges of bioconda-actions...

ci: convert autobump test to bash

---

bioconda_utils/bioconda_utils-conda_build_config.yaml

fix: update r-base pinning

---

Dockerfile

Just checking to see if changing this local location fixes the issue.

fix: try locale C.utf8

---

bioconda_utils/lint/check_repodata_patches.py

PR #855 was merged without review or, apparently, any testing :smile:

fix: Fix version number check in repodata_patches_no_version_bump()

---

bioconda_utils/build_failure.py

Include a column for the "reason" field of build failures, which hopefully helps point people in the right direction for fixing. After 80 chars, will dump the rest in a `<details>` tag to avoid table overflow.
Also list multiple rows (one per platform) instead of comma-separated strings, which do not work well in minimally-styled github wiki table.
Example of new table:

feat: improve build failure table in wiki
